// @generated by protoc-gen-es v2.14.0 with parameter "target=ts"
// @generated from file fits/api/vm/v1/os.proto (package fits.api.vm.v1, syntax proto3)
/* eslint-disable */
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../../buf/validate/validate_pb";
/**
 * Describes the file fits/api/vm/v1/os.proto.
 */
export const file_fits_api_vm_v1_os = /*@__PURE__*/ fileDesc("ChdmaXRzL2FwaS92bS92MS9vcy5wcm90bxIOZml0cy5hcGkudm0udjEiHAoCT3MSFgoEdXVpZBgBIAEoCUIIukgFcgOwAQFCpQEKEmNvbS5maXRzLmFwaS52bS52MUIHT3NQcm90b1ABWitnaXRodWIuY29tL2ZpLXRzL2FwaS9nby9maXRzL2FwaS92bS92MTt2bXYxogIDRkFWqgIORml0cy5BcGkuVm0uVjHKAg5GaXRzXEFwaVxWbVxWMeICGkZpdHNcQXBpXFZtXFYxXEdQQk1ldGFkYXRh6gIRRml0czo6QXBpOjpWbTo6VjFiBnByb3RvMw", [file_buf_validate_validate]);
/**
 * Describes the message fits.api.vm.v1.Os.
 * Use `create(OsSchema)` to create a new message.
 */
export const OsSchema = /*@__PURE__*/ messageDesc(file_fits_api_vm_v1_os, 0);
