// @generated by protoc-gen-es v2.14.1 with parameter "target=ts"
// @generated from file fits/api/vm/v1/service.proto (package fits.api.vm.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../../buf/validate/validate_pb";
import { file_fits_api_v1_common } from "../../v1/common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file fits/api/vm/v1/service.proto.
 */
export const file_fits_api_vm_v1_service: GenFile = /*@__PURE__*/
  fileDesc("ChxmaXRzL2FwaS92bS92MS9zZXJ2aWNlLnByb3RvEg5maXRzLmFwaS52bS52MSIwCgdTZXJ2aWNlEhYKBHV1aWQYASABKAlCCLpIBXIDsAEBEg0KBXRpdGxlGAIgASgJIhsKGVNlcnZpY2VTZXJ2aWNlTGlzdFJlcXVlc3QiRwoaU2VydmljZVNlcnZpY2VMaXN0UmVzcG9uc2USKQoIc2VydmljZXMYASADKAsyFy5maXRzLmFwaS52bS52MS5TZXJ2aWNlMnwKDlNlcnZpY2VTZXJ2aWNlEmoKBExpc3QSKS5maXRzLmFwaS52bS52MS5TZXJ2aWNlU2VydmljZUxpc3RSZXF1ZXN0GiouZml0cy5hcGkudm0udjEuU2VydmljZVNlcnZpY2VMaXN0UmVzcG9uc2UiC8rzGAMBAgPg8xgCQqoBChJjb20uZml0cy5hcGkudm0udjFCDFNlcnZpY2VQcm90b1ABWitnaXRodWIuY29tL2ZpLXRzL2FwaS9nby9maXRzL2FwaS92bS92MTt2bXYxogIDRkFWqgIORml0cy5BcGkuVm0uVjHKAg5GaXRzXEFwaVxWbVxWMeICGkZpdHNcQXBpXFZtXFYxXEdQQk1ldGFkYXRh6gIRRml0czo6QXBpOjpWbTo6VjFiBnByb3RvMw", [file_buf_validate_validate, file_fits_api_v1_common]);

/**
 * TODO what is a service?
 *
 * @generated from message fits.api.vm.v1.Service
 */
export type Service = Message<"fits.api.vm.v1.Service"> & {
  /**
   * Uuid of this Service
   *
   * @generated from field: string uuid = 1;
   */
  uuid: string;

  /**
   * title of the Service
   *
   * type NucleusDBServices struct {
   * 	ServiceTitle string `json:"service_title"`
   * 	ServiceUuid  string `json:"service_uuid"`
   * }
   *
   * @generated from field: string title = 2;
   */
  title: string;
};

/**
 * Describes the message fits.api.vm.v1.Service.
 * Use `create(ServiceSchema)` to create a new message.
 */
export const ServiceSchema: GenMessage<Service> = /*@__PURE__*/
  messageDesc(file_fits_api_vm_v1_service, 0);

/**
 * ServiceServiceListRequest is the request payload for a service list request.
 * The upstream nulink API accepts no body or parameters, so this is intentionally empty.
 *
 * @generated from message fits.api.vm.v1.ServiceServiceListRequest
 */
export type ServiceServiceListRequest = Message<"fits.api.vm.v1.ServiceServiceListRequest"> & {
};

/**
 * Describes the message fits.api.vm.v1.ServiceServiceListRequest.
 * Use `create(ServiceServiceListRequestSchema)` to create a new message.
 */
export const ServiceServiceListRequestSchema: GenMessage<ServiceServiceListRequest> = /*@__PURE__*/
  messageDesc(file_fits_api_vm_v1_service, 1);

/**
 * ServiceServiceListResponse is the response payload for a service list request
 *
 * @generated from message fits.api.vm.v1.ServiceServiceListResponse
 */
export type ServiceServiceListResponse = Message<"fits.api.vm.v1.ServiceServiceListResponse"> & {
  /**
   * The available services
   *
   * @generated from field: repeated fits.api.vm.v1.Service services = 1;
   */
  services: Service[];
};

/**
 * Describes the message fits.api.vm.v1.ServiceServiceListResponse.
 * Use `create(ServiceServiceListResponseSchema)` to create a new message.
 */
export const ServiceServiceListResponseSchema: GenMessage<ServiceServiceListResponse> = /*@__PURE__*/
  messageDesc(file_fits_api_vm_v1_service, 2);

/**
 * ServiceService TODO what is a service?
 *
 * @generated from service fits.api.vm.v1.ServiceService
 */
export const ServiceService: GenService<{
  /**
   * Returns a list of all services.
   *
   * @generated from rpc fits.api.vm.v1.ServiceService.List
   */
  list: {
    methodKind: "unary";
    input: typeof ServiceServiceListRequestSchema;
    output: typeof ServiceServiceListResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_fits_api_vm_v1_service, 0);

