// Code generated by generate_clients.go. DO NOT EDIT.

import { createClient, Interceptor, Transport } from "@connectrpc/connect";
import type { Client as ConnectClient } from "@connectrpc/connect";
import { createConnectTransport } from "@connectrpc/connect-web";


import { LocationService as Apimvmv1LocationService } from "./fits/api/mvm/v1/location_pb";

import { MVMService as Apimvmv1MVMService } from "./fits/api/mvm/v1/mvm_pb";

import { OSService as Apimvmv1OSService } from "./fits/api/mvm/v1/os_pb";

import { VLANService as Apimvmv1VLANService } from "./fits/api/mvm/v1/vlan_pb";



import { HealthService as Apiv1HealthService } from "./fits/api/v1/health_pb";

import { IPService as Apiv1IPService } from "./fits/api/v1/ip_pb";

import { MethodService as Apiv1MethodService } from "./fits/api/v1/method_pb";

import { ProjectService as Apiv1ProjectService } from "./fits/api/v1/project_pb";

import { TenantService as Apiv1TenantService } from "./fits/api/v1/tenant_pb";

import { TokenService as Apiv1TokenService } from "./fits/api/v1/token_pb";

import { VersionService as Apiv1VersionService } from "./fits/api/v1/version_pb";



export interface ClientConfig {
  baseUrl: string;
  token?: string;
  interceptors?: Interceptor[];
}

export interface Client {

  apimvmv1(): Apimvmv1;

  apiv1(): Apiv1;

}


export interface Apimvmv1 {

  location(): ConnectClient<typeof Apimvmv1LocationService>;

  mvm(): ConnectClient<typeof Apimvmv1MVMService>;

  os(): ConnectClient<typeof Apimvmv1OSService>;

  vlan(): ConnectClient<typeof Apimvmv1VLANService>;

}


export interface Apiv1 {

  health(): ConnectClient<typeof Apiv1HealthService>;

  ip(): ConnectClient<typeof Apiv1IPService>;

  method(): ConnectClient<typeof Apiv1MethodService>;

  project(): ConnectClient<typeof Apiv1ProjectService>;

  tenant(): ConnectClient<typeof Apiv1TenantService>;

  token(): ConnectClient<typeof Apiv1TokenService>;

  version(): ConnectClient<typeof Apiv1VersionService>;

}



function authInterceptor(token: string): Interceptor {
  return (next) => async (req) => {
    req.header.set("Authorization", `Bearer ${token}`);
    return await next(req);
  };
}

function buildTransport(config: ClientConfig): Transport {
  const interceptors: Interceptor[] = [];

  if (config.token) {
    interceptors.push(authInterceptor(config.token));
  }

  if (config.interceptors) {
    interceptors.push(...config.interceptors);
  }

  return createConnectTransport({
    baseUrl: config.baseUrl,
    interceptors: interceptors.length > 0 ? interceptors : undefined,
    defaultTimeoutMs: 30_000,
  });
}

export function newClient(config: ClientConfig): Client {
  const transport = buildTransport(config);
  return new ClientImpl(transport);
}

class ClientImpl implements Client {
  private transport: Transport;


  private _apimvmv1?: Apimvmv1Impl;

  private _apiv1?: Apiv1Impl;


  constructor(transport: Transport) {
    this.transport = transport;
  }


  apimvmv1(): Apimvmv1 {
    if (!this._apimvmv1) {
      this._apimvmv1 = new Apimvmv1Impl(this.transport);
    }
    return this._apimvmv1;
  }

  apiv1(): Apiv1 {
    if (!this._apiv1) {
      this._apiv1 = new Apiv1Impl(this.transport);
    }
    return this._apiv1;
  }

}


class Apimvmv1Impl implements Apimvmv1 {
  private transport: Transport;


  private _location?: ConnectClient<typeof Apimvmv1LocationService>;

  private _mvm?: ConnectClient<typeof Apimvmv1MVMService>;

  private _os?: ConnectClient<typeof Apimvmv1OSService>;

  private _vlan?: ConnectClient<typeof Apimvmv1VLANService>;


  constructor(transport: Transport) {
    this.transport = transport;
  }


  location(): ConnectClient<typeof Apimvmv1LocationService> {
    if (!this._location) {
      this._location = createClient(Apimvmv1LocationService, this.transport);
    }
    return this._location;
  }

  mvm(): ConnectClient<typeof Apimvmv1MVMService> {
    if (!this._mvm) {
      this._mvm = createClient(Apimvmv1MVMService, this.transport);
    }
    return this._mvm;
  }

  os(): ConnectClient<typeof Apimvmv1OSService> {
    if (!this._os) {
      this._os = createClient(Apimvmv1OSService, this.transport);
    }
    return this._os;
  }

  vlan(): ConnectClient<typeof Apimvmv1VLANService> {
    if (!this._vlan) {
      this._vlan = createClient(Apimvmv1VLANService, this.transport);
    }
    return this._vlan;
  }

}


class Apiv1Impl implements Apiv1 {
  private transport: Transport;


  private _health?: ConnectClient<typeof Apiv1HealthService>;

  private _ip?: ConnectClient<typeof Apiv1IPService>;

  private _method?: ConnectClient<typeof Apiv1MethodService>;

  private _project?: ConnectClient<typeof Apiv1ProjectService>;

  private _tenant?: ConnectClient<typeof Apiv1TenantService>;

  private _token?: ConnectClient<typeof Apiv1TokenService>;

  private _version?: ConnectClient<typeof Apiv1VersionService>;


  constructor(transport: Transport) {
    this.transport = transport;
  }


  health(): ConnectClient<typeof Apiv1HealthService> {
    if (!this._health) {
      this._health = createClient(Apiv1HealthService, this.transport);
    }
    return this._health;
  }

  ip(): ConnectClient<typeof Apiv1IPService> {
    if (!this._ip) {
      this._ip = createClient(Apiv1IPService, this.transport);
    }
    return this._ip;
  }

  method(): ConnectClient<typeof Apiv1MethodService> {
    if (!this._method) {
      this._method = createClient(Apiv1MethodService, this.transport);
    }
    return this._method;
  }

  project(): ConnectClient<typeof Apiv1ProjectService> {
    if (!this._project) {
      this._project = createClient(Apiv1ProjectService, this.transport);
    }
    return this._project;
  }

  tenant(): ConnectClient<typeof Apiv1TenantService> {
    if (!this._tenant) {
      this._tenant = createClient(Apiv1TenantService, this.transport);
    }
    return this._tenant;
  }

  token(): ConnectClient<typeof Apiv1TokenService> {
    if (!this._token) {
      this._token = createClient(Apiv1TokenService, this.transport);
    }
    return this._token;
  }

  version(): ConnectClient<typeof Apiv1VersionService> {
    if (!this._version) {
      this._version = createClient(Apiv1VersionService, this.transport);
    }
    return this._version;
  }

}


