// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: fits/api/mvm/v1/ldap.proto

package mvmv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/fi-ts/api/go/fits/api/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LDAP is an LDAP directory a Linux MVM can be integrated with.
type LDAP struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID of this LDAP directory.
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// FQDN of this LDAP directory.
	Fqdn string `protobuf:"bytes,2,opt,name=fqdn,proto3" json:"fqdn,omitempty"`
	// Tenant this LDAP directory belongs to.
	Tenant        string `protobuf:"bytes,3,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LDAP) Reset() {
	*x = LDAP{}
	mi := &file_fits_api_mvm_v1_ldap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LDAP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LDAP) ProtoMessage() {}

func (x *LDAP) ProtoReflect() protoreflect.Message {
	mi := &file_fits_api_mvm_v1_ldap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LDAP.ProtoReflect.Descriptor instead.
func (*LDAP) Descriptor() ([]byte, []int) {
	return file_fits_api_mvm_v1_ldap_proto_rawDescGZIP(), []int{0}
}

func (x *LDAP) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *LDAP) GetFqdn() string {
	if x != nil {
		return x.Fqdn
	}
	return ""
}

func (x *LDAP) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

// LDAPServiceListRequest is the request payload for an LDAP list request.
type LDAPServiceListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant to list available LDAP directories for.
	Tenant        string `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LDAPServiceListRequest) Reset() {
	*x = LDAPServiceListRequest{}
	mi := &file_fits_api_mvm_v1_ldap_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LDAPServiceListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LDAPServiceListRequest) ProtoMessage() {}

func (x *LDAPServiceListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fits_api_mvm_v1_ldap_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LDAPServiceListRequest.ProtoReflect.Descriptor instead.
func (*LDAPServiceListRequest) Descriptor() ([]byte, []int) {
	return file_fits_api_mvm_v1_ldap_proto_rawDescGZIP(), []int{1}
}

func (x *LDAPServiceListRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

// LDAPServiceListResponse is the response payload for an LDAP list request.
type LDAPServiceListResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The available LDAP directories.
	Ldaps         []*LDAP `protobuf:"bytes,1,rep,name=ldaps,proto3" json:"ldaps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LDAPServiceListResponse) Reset() {
	*x = LDAPServiceListResponse{}
	mi := &file_fits_api_mvm_v1_ldap_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LDAPServiceListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LDAPServiceListResponse) ProtoMessage() {}

func (x *LDAPServiceListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fits_api_mvm_v1_ldap_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LDAPServiceListResponse.ProtoReflect.Descriptor instead.
func (*LDAPServiceListResponse) Descriptor() ([]byte, []int) {
	return file_fits_api_mvm_v1_ldap_proto_rawDescGZIP(), []int{2}
}

func (x *LDAPServiceListResponse) GetLdaps() []*LDAP {
	if x != nil {
		return x.Ldaps
	}
	return nil
}

var File_fits_api_mvm_v1_ldap_proto protoreflect.FileDescriptor

const file_fits_api_mvm_v1_ldap_proto_rawDesc = "" +
	"\n" +
	"\x1afits/api/mvm/v1/ldap.proto\x12\x0ffits.api.mvm.v1\x1a\x1bbuf/validate/validate.proto\x1a\x18fits/api/v1/common.proto\x1a\"fits/api/v1/predefined_rules.proto\"j\n" +
	"\x04LDAP\x12\x1c\n" +
	"\x04uuid\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x04uuid\x12\x1f\n" +
	"\x04fqdn\x18\x02 \x01(\tB\v\xbaH\br\x06\xc0\xb3\xae\xb1\x02\x01R\x04fqdn\x12#\n" +
	"\x06tenant\x18\x03 \x01(\tB\v\xbaH\br\x06\xc0\xb3\xae\xb1\x02\x01R\x06tenant\"=\n" +
	"\x16LDAPServiceListRequest\x12#\n" +
	"\x06tenant\x18\x01 \x01(\tB\v\xbaH\br\x06\xc0\xb3\xae\xb1\x02\x01R\x06tenant\"F\n" +
	"\x17LDAPServiceListResponse\x12+\n" +
	"\x05ldaps\x18\x01 \x03(\v2\x15.fits.api.mvm.v1.LDAPR\x05ldaps2u\n" +
	"\vLDAPService\x12f\n" +
	"\x04List\x12'.fits.api.mvm.v1.LDAPServiceListRequest\x1a(.fits.api.mvm.v1.LDAPServiceListResponse\"\v\xc2\xf3\x18\x03\x01\x02\x03\xe0\xf3\x18\x02B\xae\x01\n" +
	"\x13com.fits.api.mvm.v1B\tLdapProtoP\x01Z-github.com/fi-ts/api/go/fits/api/mvm/v1;mvmv1\xa2\x02\x03FAM\xaa\x02\x0fFits.Api.Mvm.V1\xca\x02\x0fFits\\Api\\Mvm\\V1\xe2\x02\x1bFits\\Api\\Mvm\\V1\\GPBMetadata\xea\x02\x12Fits::Api::Mvm::V1b\x06proto3"

var (
	file_fits_api_mvm_v1_ldap_proto_rawDescOnce sync.Once
	file_fits_api_mvm_v1_ldap_proto_rawDescData []byte
)

func file_fits_api_mvm_v1_ldap_proto_rawDescGZIP() []byte {
	file_fits_api_mvm_v1_ldap_proto_rawDescOnce.Do(func() {
		file_fits_api_mvm_v1_ldap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fits_api_mvm_v1_ldap_proto_rawDesc), len(file_fits_api_mvm_v1_ldap_proto_rawDesc)))
	})
	return file_fits_api_mvm_v1_ldap_proto_rawDescData
}

var file_fits_api_mvm_v1_ldap_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_fits_api_mvm_v1_ldap_proto_goTypes = []any{
	(*LDAP)(nil),                    // 0: fits.api.mvm.v1.LDAP
	(*LDAPServiceListRequest)(nil),  // 1: fits.api.mvm.v1.LDAPServiceListRequest
	(*LDAPServiceListResponse)(nil), // 2: fits.api.mvm.v1.LDAPServiceListResponse
}
var file_fits_api_mvm_v1_ldap_proto_depIdxs = []int32{
	0, // 0: fits.api.mvm.v1.LDAPServiceListResponse.ldaps:type_name -> fits.api.mvm.v1.LDAP
	1, // 1: fits.api.mvm.v1.LDAPService.List:input_type -> fits.api.mvm.v1.LDAPServiceListRequest
	2, // 2: fits.api.mvm.v1.LDAPService.List:output_type -> fits.api.mvm.v1.LDAPServiceListResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_fits_api_mvm_v1_ldap_proto_init() }
func file_fits_api_mvm_v1_ldap_proto_init() {
	if File_fits_api_mvm_v1_ldap_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fits_api_mvm_v1_ldap_proto_rawDesc), len(file_fits_api_mvm_v1_ldap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fits_api_mvm_v1_ldap_proto_goTypes,
		DependencyIndexes: file_fits_api_mvm_v1_ldap_proto_depIdxs,
		MessageInfos:      file_fits_api_mvm_v1_ldap_proto_msgTypes,
	}.Build()
	File_fits_api_mvm_v1_ldap_proto = out.File
	file_fits_api_mvm_v1_ldap_proto_goTypes = nil
	file_fits_api_mvm_v1_ldap_proto_depIdxs = nil
}
