// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package vmv1connect

import (
	"context"

	"github.com/fi-ts/api/go/fits/api/vm/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewVMServiceHandler creates a new instance of VMServiceHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVMServiceHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *VMServiceHandler {
	mock := &VMServiceHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// VMServiceHandler is an autogenerated mock type for the VMServiceHandler type
type VMServiceHandler struct {
	mock.Mock
}

type VMServiceHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *VMServiceHandler) EXPECT() *VMServiceHandler_Expecter {
	return &VMServiceHandler_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type VMServiceHandler
func (_mock *VMServiceHandler) Create(context1 context.Context, vMServiceCreateRequest *vmv1.VMServiceCreateRequest) (*vmv1.VMServiceCreateResponse, error) {
	ret := _mock.Called(context1, vMServiceCreateRequest)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *vmv1.VMServiceCreateResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *vmv1.VMServiceCreateRequest) (*vmv1.VMServiceCreateResponse, error)); ok {
		return returnFunc(context1, vMServiceCreateRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *vmv1.VMServiceCreateRequest) *vmv1.VMServiceCreateResponse); ok {
		r0 = returnFunc(context1, vMServiceCreateRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vmv1.VMServiceCreateResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *vmv1.VMServiceCreateRequest) error); ok {
		r1 = returnFunc(context1, vMServiceCreateRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// VMServiceHandler_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type VMServiceHandler_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - vMServiceCreateRequest *vmv1.VMServiceCreateRequest
func (_e *VMServiceHandler_Expecter) Create(context1 any, vMServiceCreateRequest any) *VMServiceHandler_Create_Call {
	return &VMServiceHandler_Create_Call{Call: _e.mock.On("Create", context1, vMServiceCreateRequest)}
}

func (_c *VMServiceHandler_Create_Call) Run(run func(context1 context.Context, vMServiceCreateRequest *vmv1.VMServiceCreateRequest)) *VMServiceHandler_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *vmv1.VMServiceCreateRequest
		if args[1] != nil {
			arg1 = args[1].(*vmv1.VMServiceCreateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *VMServiceHandler_Create_Call) Return(vMServiceCreateResponse *vmv1.VMServiceCreateResponse, err error) *VMServiceHandler_Create_Call {
	_c.Call.Return(vMServiceCreateResponse, err)
	return _c
}

func (_c *VMServiceHandler_Create_Call) RunAndReturn(run func(context1 context.Context, vMServiceCreateRequest *vmv1.VMServiceCreateRequest) (*vmv1.VMServiceCreateResponse, error)) *VMServiceHandler_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type VMServiceHandler
func (_mock *VMServiceHandler) Delete(context1 context.Context, vMServiceDeleteRequest *vmv1.VMServiceDeleteRequest) (*vmv1.VMServiceDeleteResponse, error) {
	ret := _mock.Called(context1, vMServiceDeleteRequest)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *vmv1.VMServiceDeleteResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *vmv1.VMServiceDeleteRequest) (*vmv1.VMServiceDeleteResponse, error)); ok {
		return returnFunc(context1, vMServiceDeleteRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *vmv1.VMServiceDeleteRequest) *vmv1.VMServiceDeleteResponse); ok {
		r0 = returnFunc(context1, vMServiceDeleteRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vmv1.VMServiceDeleteResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *vmv1.VMServiceDeleteRequest) error); ok {
		r1 = returnFunc(context1, vMServiceDeleteRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// VMServiceHandler_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type VMServiceHandler_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - context1 context.Context
//   - vMServiceDeleteRequest *vmv1.VMServiceDeleteRequest
func (_e *VMServiceHandler_Expecter) Delete(context1 any, vMServiceDeleteRequest any) *VMServiceHandler_Delete_Call {
	return &VMServiceHandler_Delete_Call{Call: _e.mock.On("Delete", context1, vMServiceDeleteRequest)}
}

func (_c *VMServiceHandler_Delete_Call) Run(run func(context1 context.Context, vMServiceDeleteRequest *vmv1.VMServiceDeleteRequest)) *VMServiceHandler_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *vmv1.VMServiceDeleteRequest
		if args[1] != nil {
			arg1 = args[1].(*vmv1.VMServiceDeleteRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *VMServiceHandler_Delete_Call) Return(vMServiceDeleteResponse *vmv1.VMServiceDeleteResponse, err error) *VMServiceHandler_Delete_Call {
	_c.Call.Return(vMServiceDeleteResponse, err)
	return _c
}

func (_c *VMServiceHandler_Delete_Call) RunAndReturn(run func(context1 context.Context, vMServiceDeleteRequest *vmv1.VMServiceDeleteRequest) (*vmv1.VMServiceDeleteResponse, error)) *VMServiceHandler_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type VMServiceHandler
func (_mock *VMServiceHandler) Get(context1 context.Context, vMServiceGetRequest *vmv1.VMServiceGetRequest) (*vmv1.VMServiceGetResponse, error) {
	ret := _mock.Called(context1, vMServiceGetRequest)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *vmv1.VMServiceGetResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *vmv1.VMServiceGetRequest) (*vmv1.VMServiceGetResponse, error)); ok {
		return returnFunc(context1, vMServiceGetRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *vmv1.VMServiceGetRequest) *vmv1.VMServiceGetResponse); ok {
		r0 = returnFunc(context1, vMServiceGetRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vmv1.VMServiceGetResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *vmv1.VMServiceGetRequest) error); ok {
		r1 = returnFunc(context1, vMServiceGetRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// VMServiceHandler_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type VMServiceHandler_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - context1 context.Context
//   - vMServiceGetRequest *vmv1.VMServiceGetRequest
func (_e *VMServiceHandler_Expecter) Get(context1 any, vMServiceGetRequest any) *VMServiceHandler_Get_Call {
	return &VMServiceHandler_Get_Call{Call: _e.mock.On("Get", context1, vMServiceGetRequest)}
}

func (_c *VMServiceHandler_Get_Call) Run(run func(context1 context.Context, vMServiceGetRequest *vmv1.VMServiceGetRequest)) *VMServiceHandler_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *vmv1.VMServiceGetRequest
		if args[1] != nil {
			arg1 = args[1].(*vmv1.VMServiceGetRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *VMServiceHandler_Get_Call) Return(vMServiceGetResponse *vmv1.VMServiceGetResponse, err error) *VMServiceHandler_Get_Call {
	_c.Call.Return(vMServiceGetResponse, err)
	return _c
}

func (_c *VMServiceHandler_Get_Call) RunAndReturn(run func(context1 context.Context, vMServiceGetRequest *vmv1.VMServiceGetRequest) (*vmv1.VMServiceGetResponse, error)) *VMServiceHandler_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type VMServiceHandler
func (_mock *VMServiceHandler) List(context1 context.Context, vMServiceListRequest *vmv1.VMServiceListRequest) (*vmv1.VMServiceListResponse, error) {
	ret := _mock.Called(context1, vMServiceListRequest)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *vmv1.VMServiceListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *vmv1.VMServiceListRequest) (*vmv1.VMServiceListResponse, error)); ok {
		return returnFunc(context1, vMServiceListRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *vmv1.VMServiceListRequest) *vmv1.VMServiceListResponse); ok {
		r0 = returnFunc(context1, vMServiceListRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vmv1.VMServiceListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *vmv1.VMServiceListRequest) error); ok {
		r1 = returnFunc(context1, vMServiceListRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// VMServiceHandler_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type VMServiceHandler_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - context1 context.Context
//   - vMServiceListRequest *vmv1.VMServiceListRequest
func (_e *VMServiceHandler_Expecter) List(context1 any, vMServiceListRequest any) *VMServiceHandler_List_Call {
	return &VMServiceHandler_List_Call{Call: _e.mock.On("List", context1, vMServiceListRequest)}
}

func (_c *VMServiceHandler_List_Call) Run(run func(context1 context.Context, vMServiceListRequest *vmv1.VMServiceListRequest)) *VMServiceHandler_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *vmv1.VMServiceListRequest
		if args[1] != nil {
			arg1 = args[1].(*vmv1.VMServiceListRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *VMServiceHandler_List_Call) Return(vMServiceListResponse *vmv1.VMServiceListResponse, err error) *VMServiceHandler_List_Call {
	_c.Call.Return(vMServiceListResponse, err)
	return _c
}

func (_c *VMServiceHandler_List_Call) RunAndReturn(run func(context1 context.Context, vMServiceListRequest *vmv1.VMServiceListRequest) (*vmv1.VMServiceListResponse, error)) *VMServiceHandler_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type VMServiceHandler
func (_mock *VMServiceHandler) Update(context1 context.Context, vMServiceUpdateRequest *vmv1.VMServiceUpdateRequest) (*vmv1.VMServiceUpdateResponse, error) {
	ret := _mock.Called(context1, vMServiceUpdateRequest)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *vmv1.VMServiceUpdateResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *vmv1.VMServiceUpdateRequest) (*vmv1.VMServiceUpdateResponse, error)); ok {
		return returnFunc(context1, vMServiceUpdateRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *vmv1.VMServiceUpdateRequest) *vmv1.VMServiceUpdateResponse); ok {
		r0 = returnFunc(context1, vMServiceUpdateRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vmv1.VMServiceUpdateResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *vmv1.VMServiceUpdateRequest) error); ok {
		r1 = returnFunc(context1, vMServiceUpdateRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// VMServiceHandler_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type VMServiceHandler_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - context1 context.Context
//   - vMServiceUpdateRequest *vmv1.VMServiceUpdateRequest
func (_e *VMServiceHandler_Expecter) Update(context1 any, vMServiceUpdateRequest any) *VMServiceHandler_Update_Call {
	return &VMServiceHandler_Update_Call{Call: _e.mock.On("Update", context1, vMServiceUpdateRequest)}
}

func (_c *VMServiceHandler_Update_Call) Run(run func(context1 context.Context, vMServiceUpdateRequest *vmv1.VMServiceUpdateRequest)) *VMServiceHandler_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *vmv1.VMServiceUpdateRequest
		if args[1] != nil {
			arg1 = args[1].(*vmv1.VMServiceUpdateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *VMServiceHandler_Update_Call) Return(vMServiceUpdateResponse *vmv1.VMServiceUpdateResponse, err error) *VMServiceHandler_Update_Call {
	_c.Call.Return(vMServiceUpdateResponse, err)
	return _c
}

func (_c *VMServiceHandler_Update_Call) RunAndReturn(run func(context1 context.Context, vMServiceUpdateRequest *vmv1.VMServiceUpdateRequest) (*vmv1.VMServiceUpdateResponse, error)) *VMServiceHandler_Update_Call {
	_c.Call.Return(run)
	return _c
}
