// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: fits/api/v1/ip.proto

package apiv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/fi-ts/api/go/fits/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// IPServiceName is the fully-qualified name of the IPService service.
	IPServiceName = "fits.api.v1.IPService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// IPServiceGetProcedure is the fully-qualified name of the IPService's Get RPC.
	IPServiceGetProcedure = "/fits.api.v1.IPService/Get"
	// IPServiceCreateProcedure is the fully-qualified name of the IPService's Create RPC.
	IPServiceCreateProcedure = "/fits.api.v1.IPService/Create"
	// IPServiceUpdateProcedure is the fully-qualified name of the IPService's Update RPC.
	IPServiceUpdateProcedure = "/fits.api.v1.IPService/Update"
	// IPServiceListProcedure is the fully-qualified name of the IPService's List RPC.
	IPServiceListProcedure = "/fits.api.v1.IPService/List"
	// IPServiceDeleteProcedure is the fully-qualified name of the IPService's Delete RPC.
	IPServiceDeleteProcedure = "/fits.api.v1.IPService/Delete"
)

// IPServiceClient is a client for the fits.api.v1.IPService service.
type IPServiceClient interface {
	// Returns the IP address with the specified IP.
	Get(context.Context, *v1.IPServiceGetRequest) (*v1.IPServiceGetResponse, error)
	// Creates a new IP address.
	Create(context.Context, *v1.IPServiceCreateRequest) (*v1.IPServiceCreateResponse, error)
	// Updates an IP address.
	Update(context.Context, *v1.IPServiceUpdateRequest) (*v1.IPServiceUpdateResponse, error)
	// Returns the list of all IP addresses.
	List(context.Context, *v1.IPServiceListRequest) (*v1.IPServiceListResponse, error)
	// Deletes an IP address.
	Delete(context.Context, *v1.IPServiceDeleteRequest) (*v1.IPServiceDeleteResponse, error)
}

// NewIPServiceClient constructs a client for the fits.api.v1.IPService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewIPServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) IPServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	iPServiceMethods := v1.File_fits_api_v1_ip_proto.Services().ByName("IPService").Methods()
	return &iPServiceClient{
		get: connect.NewClient[v1.IPServiceGetRequest, v1.IPServiceGetResponse](
			httpClient,
			baseURL+IPServiceGetProcedure,
			connect.WithSchema(iPServiceMethods.ByName("Get")),
			connect.WithClientOptions(opts...),
		),
		create: connect.NewClient[v1.IPServiceCreateRequest, v1.IPServiceCreateResponse](
			httpClient,
			baseURL+IPServiceCreateProcedure,
			connect.WithSchema(iPServiceMethods.ByName("Create")),
			connect.WithClientOptions(opts...),
		),
		update: connect.NewClient[v1.IPServiceUpdateRequest, v1.IPServiceUpdateResponse](
			httpClient,
			baseURL+IPServiceUpdateProcedure,
			connect.WithSchema(iPServiceMethods.ByName("Update")),
			connect.WithClientOptions(opts...),
		),
		list: connect.NewClient[v1.IPServiceListRequest, v1.IPServiceListResponse](
			httpClient,
			baseURL+IPServiceListProcedure,
			connect.WithSchema(iPServiceMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
		delete: connect.NewClient[v1.IPServiceDeleteRequest, v1.IPServiceDeleteResponse](
			httpClient,
			baseURL+IPServiceDeleteProcedure,
			connect.WithSchema(iPServiceMethods.ByName("Delete")),
			connect.WithClientOptions(opts...),
		),
	}
}

// iPServiceClient implements IPServiceClient.
type iPServiceClient struct {
	get    *connect.Client[v1.IPServiceGetRequest, v1.IPServiceGetResponse]
	create *connect.Client[v1.IPServiceCreateRequest, v1.IPServiceCreateResponse]
	update *connect.Client[v1.IPServiceUpdateRequest, v1.IPServiceUpdateResponse]
	list   *connect.Client[v1.IPServiceListRequest, v1.IPServiceListResponse]
	delete *connect.Client[v1.IPServiceDeleteRequest, v1.IPServiceDeleteResponse]
}

// Get calls fits.api.v1.IPService.Get.
func (c *iPServiceClient) Get(ctx context.Context, req *v1.IPServiceGetRequest) (*v1.IPServiceGetResponse, error) {
	response, err := c.get.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// Create calls fits.api.v1.IPService.Create.
func (c *iPServiceClient) Create(ctx context.Context, req *v1.IPServiceCreateRequest) (*v1.IPServiceCreateResponse, error) {
	response, err := c.create.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// Update calls fits.api.v1.IPService.Update.
func (c *iPServiceClient) Update(ctx context.Context, req *v1.IPServiceUpdateRequest) (*v1.IPServiceUpdateResponse, error) {
	response, err := c.update.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// List calls fits.api.v1.IPService.List.
func (c *iPServiceClient) List(ctx context.Context, req *v1.IPServiceListRequest) (*v1.IPServiceListResponse, error) {
	response, err := c.list.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// Delete calls fits.api.v1.IPService.Delete.
func (c *iPServiceClient) Delete(ctx context.Context, req *v1.IPServiceDeleteRequest) (*v1.IPServiceDeleteResponse, error) {
	response, err := c.delete.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// IPServiceHandler is an implementation of the fits.api.v1.IPService service.
type IPServiceHandler interface {
	// Returns the IP address with the specified IP.
	Get(context.Context, *v1.IPServiceGetRequest) (*v1.IPServiceGetResponse, error)
	// Creates a new IP address.
	Create(context.Context, *v1.IPServiceCreateRequest) (*v1.IPServiceCreateResponse, error)
	// Updates an IP address.
	Update(context.Context, *v1.IPServiceUpdateRequest) (*v1.IPServiceUpdateResponse, error)
	// Returns the list of all IP addresses.
	List(context.Context, *v1.IPServiceListRequest) (*v1.IPServiceListResponse, error)
	// Deletes an IP address.
	Delete(context.Context, *v1.IPServiceDeleteRequest) (*v1.IPServiceDeleteResponse, error)
}

// NewIPServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewIPServiceHandler(svc IPServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	iPServiceMethods := v1.File_fits_api_v1_ip_proto.Services().ByName("IPService").Methods()
	iPServiceGetHandler := connect.NewUnaryHandlerSimple(
		IPServiceGetProcedure,
		svc.Get,
		connect.WithSchema(iPServiceMethods.ByName("Get")),
		connect.WithHandlerOptions(opts...),
	)
	iPServiceCreateHandler := connect.NewUnaryHandlerSimple(
		IPServiceCreateProcedure,
		svc.Create,
		connect.WithSchema(iPServiceMethods.ByName("Create")),
		connect.WithHandlerOptions(opts...),
	)
	iPServiceUpdateHandler := connect.NewUnaryHandlerSimple(
		IPServiceUpdateProcedure,
		svc.Update,
		connect.WithSchema(iPServiceMethods.ByName("Update")),
		connect.WithHandlerOptions(opts...),
	)
	iPServiceListHandler := connect.NewUnaryHandlerSimple(
		IPServiceListProcedure,
		svc.List,
		connect.WithSchema(iPServiceMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	iPServiceDeleteHandler := connect.NewUnaryHandlerSimple(
		IPServiceDeleteProcedure,
		svc.Delete,
		connect.WithSchema(iPServiceMethods.ByName("Delete")),
		connect.WithHandlerOptions(opts...),
	)
	return "/fits.api.v1.IPService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case IPServiceGetProcedure:
			iPServiceGetHandler.ServeHTTP(w, r)
		case IPServiceCreateProcedure:
			iPServiceCreateHandler.ServeHTTP(w, r)
		case IPServiceUpdateProcedure:
			iPServiceUpdateHandler.ServeHTTP(w, r)
		case IPServiceListProcedure:
			iPServiceListHandler.ServeHTTP(w, r)
		case IPServiceDeleteProcedure:
			iPServiceDeleteHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedIPServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedIPServiceHandler struct{}

func (UnimplementedIPServiceHandler) Get(context.Context, *v1.IPServiceGetRequest) (*v1.IPServiceGetResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("fits.api.v1.IPService.Get is not implemented"))
}

func (UnimplementedIPServiceHandler) Create(context.Context, *v1.IPServiceCreateRequest) (*v1.IPServiceCreateResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("fits.api.v1.IPService.Create is not implemented"))
}

func (UnimplementedIPServiceHandler) Update(context.Context, *v1.IPServiceUpdateRequest) (*v1.IPServiceUpdateResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("fits.api.v1.IPService.Update is not implemented"))
}

func (UnimplementedIPServiceHandler) List(context.Context, *v1.IPServiceListRequest) (*v1.IPServiceListResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("fits.api.v1.IPService.List is not implemented"))
}

func (UnimplementedIPServiceHandler) Delete(context.Context, *v1.IPServiceDeleteRequest) (*v1.IPServiceDeleteResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("fits.api.v1.IPService.Delete is not implemented"))
}
