// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: fits/api/v1/tenant.proto

package apiv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/fi-ts/api/go/fits/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TenantServiceName is the fully-qualified name of the TenantService service.
	TenantServiceName = "fits.api.v1.TenantService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TenantServiceCreateProcedure is the fully-qualified name of the TenantService's Create RPC.
	TenantServiceCreateProcedure = "/fits.api.v1.TenantService/Create"
	// TenantServiceListProcedure is the fully-qualified name of the TenantService's List RPC.
	TenantServiceListProcedure = "/fits.api.v1.TenantService/List"
	// TenantServiceGetProcedure is the fully-qualified name of the TenantService's Get RPC.
	TenantServiceGetProcedure = "/fits.api.v1.TenantService/Get"
	// TenantServiceUpdateProcedure is the fully-qualified name of the TenantService's Update RPC.
	TenantServiceUpdateProcedure = "/fits.api.v1.TenantService/Update"
	// TenantServiceDeleteProcedure is the fully-qualified name of the TenantService's Delete RPC.
	TenantServiceDeleteProcedure = "/fits.api.v1.TenantService/Delete"
)

// TenantServiceClient is a client for the fits.api.v1.TenantService service.
type TenantServiceClient interface {
	// Creates a new tenant.
	Create(context.Context, *v1.TenantServiceCreateRequest) (*v1.TenantServiceCreateResponse, error)
	// Returns the list of tenants.
	List(context.Context, *v1.TenantServiceListRequest) (*v1.TenantServiceListResponse, error)
	// Get a tenant
	Get(context.Context, *v1.TenantServiceGetRequest) (*v1.TenantServiceGetResponse, error)
	// Update a tenant
	Update(context.Context, *v1.TenantServiceUpdateRequest) (*v1.TenantServiceUpdateResponse, error)
	// Delete a tenant
	Delete(context.Context, *v1.TenantServiceDeleteRequest) (*v1.TenantServiceDeleteResponse, error)
}

// NewTenantServiceClient constructs a client for the fits.api.v1.TenantService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTenantServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TenantServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	tenantServiceMethods := v1.File_fits_api_v1_tenant_proto.Services().ByName("TenantService").Methods()
	return &tenantServiceClient{
		create: connect.NewClient[v1.TenantServiceCreateRequest, v1.TenantServiceCreateResponse](
			httpClient,
			baseURL+TenantServiceCreateProcedure,
			connect.WithSchema(tenantServiceMethods.ByName("Create")),
			connect.WithClientOptions(opts...),
		),
		list: connect.NewClient[v1.TenantServiceListRequest, v1.TenantServiceListResponse](
			httpClient,
			baseURL+TenantServiceListProcedure,
			connect.WithSchema(tenantServiceMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
		get: connect.NewClient[v1.TenantServiceGetRequest, v1.TenantServiceGetResponse](
			httpClient,
			baseURL+TenantServiceGetProcedure,
			connect.WithSchema(tenantServiceMethods.ByName("Get")),
			connect.WithClientOptions(opts...),
		),
		update: connect.NewClient[v1.TenantServiceUpdateRequest, v1.TenantServiceUpdateResponse](
			httpClient,
			baseURL+TenantServiceUpdateProcedure,
			connect.WithSchema(tenantServiceMethods.ByName("Update")),
			connect.WithClientOptions(opts...),
		),
		delete: connect.NewClient[v1.TenantServiceDeleteRequest, v1.TenantServiceDeleteResponse](
			httpClient,
			baseURL+TenantServiceDeleteProcedure,
			connect.WithSchema(tenantServiceMethods.ByName("Delete")),
			connect.WithClientOptions(opts...),
		),
	}
}

// tenantServiceClient implements TenantServiceClient.
type tenantServiceClient struct {
	create *connect.Client[v1.TenantServiceCreateRequest, v1.TenantServiceCreateResponse]
	list   *connect.Client[v1.TenantServiceListRequest, v1.TenantServiceListResponse]
	get    *connect.Client[v1.TenantServiceGetRequest, v1.TenantServiceGetResponse]
	update *connect.Client[v1.TenantServiceUpdateRequest, v1.TenantServiceUpdateResponse]
	delete *connect.Client[v1.TenantServiceDeleteRequest, v1.TenantServiceDeleteResponse]
}

// Create calls fits.api.v1.TenantService.Create.
func (c *tenantServiceClient) Create(ctx context.Context, req *v1.TenantServiceCreateRequest) (*v1.TenantServiceCreateResponse, error) {
	response, err := c.create.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// List calls fits.api.v1.TenantService.List.
func (c *tenantServiceClient) List(ctx context.Context, req *v1.TenantServiceListRequest) (*v1.TenantServiceListResponse, error) {
	response, err := c.list.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// Get calls fits.api.v1.TenantService.Get.
func (c *tenantServiceClient) Get(ctx context.Context, req *v1.TenantServiceGetRequest) (*v1.TenantServiceGetResponse, error) {
	response, err := c.get.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// Update calls fits.api.v1.TenantService.Update.
func (c *tenantServiceClient) Update(ctx context.Context, req *v1.TenantServiceUpdateRequest) (*v1.TenantServiceUpdateResponse, error) {
	response, err := c.update.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// Delete calls fits.api.v1.TenantService.Delete.
func (c *tenantServiceClient) Delete(ctx context.Context, req *v1.TenantServiceDeleteRequest) (*v1.TenantServiceDeleteResponse, error) {
	response, err := c.delete.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// TenantServiceHandler is an implementation of the fits.api.v1.TenantService service.
type TenantServiceHandler interface {
	// Creates a new tenant.
	Create(context.Context, *v1.TenantServiceCreateRequest) (*v1.TenantServiceCreateResponse, error)
	// Returns the list of tenants.
	List(context.Context, *v1.TenantServiceListRequest) (*v1.TenantServiceListResponse, error)
	// Get a tenant
	Get(context.Context, *v1.TenantServiceGetRequest) (*v1.TenantServiceGetResponse, error)
	// Update a tenant
	Update(context.Context, *v1.TenantServiceUpdateRequest) (*v1.TenantServiceUpdateResponse, error)
	// Delete a tenant
	Delete(context.Context, *v1.TenantServiceDeleteRequest) (*v1.TenantServiceDeleteResponse, error)
}

// NewTenantServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTenantServiceHandler(svc TenantServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	tenantServiceMethods := v1.File_fits_api_v1_tenant_proto.Services().ByName("TenantService").Methods()
	tenantServiceCreateHandler := connect.NewUnaryHandlerSimple(
		TenantServiceCreateProcedure,
		svc.Create,
		connect.WithSchema(tenantServiceMethods.ByName("Create")),
		connect.WithHandlerOptions(opts...),
	)
	tenantServiceListHandler := connect.NewUnaryHandlerSimple(
		TenantServiceListProcedure,
		svc.List,
		connect.WithSchema(tenantServiceMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	tenantServiceGetHandler := connect.NewUnaryHandlerSimple(
		TenantServiceGetProcedure,
		svc.Get,
		connect.WithSchema(tenantServiceMethods.ByName("Get")),
		connect.WithHandlerOptions(opts...),
	)
	tenantServiceUpdateHandler := connect.NewUnaryHandlerSimple(
		TenantServiceUpdateProcedure,
		svc.Update,
		connect.WithSchema(tenantServiceMethods.ByName("Update")),
		connect.WithHandlerOptions(opts...),
	)
	tenantServiceDeleteHandler := connect.NewUnaryHandlerSimple(
		TenantServiceDeleteProcedure,
		svc.Delete,
		connect.WithSchema(tenantServiceMethods.ByName("Delete")),
		connect.WithHandlerOptions(opts...),
	)
	return "/fits.api.v1.TenantService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TenantServiceCreateProcedure:
			tenantServiceCreateHandler.ServeHTTP(w, r)
		case TenantServiceListProcedure:
			tenantServiceListHandler.ServeHTTP(w, r)
		case TenantServiceGetProcedure:
			tenantServiceGetHandler.ServeHTTP(w, r)
		case TenantServiceUpdateProcedure:
			tenantServiceUpdateHandler.ServeHTTP(w, r)
		case TenantServiceDeleteProcedure:
			tenantServiceDeleteHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTenantServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTenantServiceHandler struct{}

func (UnimplementedTenantServiceHandler) Create(context.Context, *v1.TenantServiceCreateRequest) (*v1.TenantServiceCreateResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("fits.api.v1.TenantService.Create is not implemented"))
}

func (UnimplementedTenantServiceHandler) List(context.Context, *v1.TenantServiceListRequest) (*v1.TenantServiceListResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("fits.api.v1.TenantService.List is not implemented"))
}

func (UnimplementedTenantServiceHandler) Get(context.Context, *v1.TenantServiceGetRequest) (*v1.TenantServiceGetResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("fits.api.v1.TenantService.Get is not implemented"))
}

func (UnimplementedTenantServiceHandler) Update(context.Context, *v1.TenantServiceUpdateRequest) (*v1.TenantServiceUpdateResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("fits.api.v1.TenantService.Update is not implemented"))
}

func (UnimplementedTenantServiceHandler) Delete(context.Context, *v1.TenantServiceDeleteRequest) (*v1.TenantServiceDeleteResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("fits.api.v1.TenantService.Delete is not implemented"))
}
