# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: fits/api/vm/v1/vm.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.codec import Codec
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import fits.api.vm.v1.vm_pb2 as fits_dot_api_dot_vm_dot_v1_dot_vm__pb2


class VMService(Protocol):
    async def get(self, request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceGetRequest, ctx: RequestContext) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceGetResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def create(self, request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceCreateRequest, ctx: RequestContext) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceCreateResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def update(self, request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceUpdateRequest, ctx: RequestContext) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceUpdateResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list(self, request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceListRequest, ctx: RequestContext) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceListResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete(self, request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceDeleteRequest, ctx: RequestContext) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceDeleteResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def add_disk(self, request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceAddDiskRequest, ctx: RequestContext) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceAddDiskResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def update_disk(self, request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceUpdateDiskRequest, ctx: RequestContext) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceUpdateDiskResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_disk(self, request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceDeleteDiskRequest, ctx: RequestContext) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceDeleteDiskResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def add_i_p(self, request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceAddIPRequest, ctx: RequestContext) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceAddIPResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def move_i_p(self, request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceMoveIPRequest, ctx: RequestContext) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceMoveIPResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_i_p(self, request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceDeleteIPRequest, ctx: RequestContext) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceDeleteIPResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def validate_create(self, request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateCreateRequest, ctx: RequestContext) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateCreateResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def validate_add_disk(self, request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateAddDiskRequest, ctx: RequestContext) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateAddDiskResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def validate_update_disk(self, request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateUpdateDiskRequest, ctx: RequestContext) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateUpdateDiskResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def validate_add_i_p(self, request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateAddIPRequest, ctx: RequestContext) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateAddIPResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class VMServiceASGIApplication(ConnectASGIApplication[VMService]):
    def __init__(self, service: VMService | AsyncGenerator[VMService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/fits.api.vm.v1.VMService/Get": Endpoint.unary(
                    method=MethodInfo(
                        name="Get",
                        service_name="fits.api.vm.v1.VMService",
                        input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceGetRequest,
                        output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceGetResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get,
                ),
                "/fits.api.vm.v1.VMService/Create": Endpoint.unary(
                    method=MethodInfo(
                        name="Create",
                        service_name="fits.api.vm.v1.VMService",
                        input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceCreateRequest,
                        output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceCreateResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create,
                ),
                "/fits.api.vm.v1.VMService/Update": Endpoint.unary(
                    method=MethodInfo(
                        name="Update",
                        service_name="fits.api.vm.v1.VMService",
                        input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceUpdateRequest,
                        output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceUpdateResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.update,
                ),
                "/fits.api.vm.v1.VMService/List": Endpoint.unary(
                    method=MethodInfo(
                        name="List",
                        service_name="fits.api.vm.v1.VMService",
                        input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceListRequest,
                        output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceListResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list,
                ),
                "/fits.api.vm.v1.VMService/Delete": Endpoint.unary(
                    method=MethodInfo(
                        name="Delete",
                        service_name="fits.api.vm.v1.VMService",
                        input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceDeleteRequest,
                        output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceDeleteResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete,
                ),
                "/fits.api.vm.v1.VMService/AddDisk": Endpoint.unary(
                    method=MethodInfo(
                        name="AddDisk",
                        service_name="fits.api.vm.v1.VMService",
                        input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceAddDiskRequest,
                        output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceAddDiskResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.add_disk,
                ),
                "/fits.api.vm.v1.VMService/UpdateDisk": Endpoint.unary(
                    method=MethodInfo(
                        name="UpdateDisk",
                        service_name="fits.api.vm.v1.VMService",
                        input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceUpdateDiskRequest,
                        output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceUpdateDiskResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.update_disk,
                ),
                "/fits.api.vm.v1.VMService/DeleteDisk": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteDisk",
                        service_name="fits.api.vm.v1.VMService",
                        input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceDeleteDiskRequest,
                        output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceDeleteDiskResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_disk,
                ),
                "/fits.api.vm.v1.VMService/AddIP": Endpoint.unary(
                    method=MethodInfo(
                        name="AddIP",
                        service_name="fits.api.vm.v1.VMService",
                        input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceAddIPRequest,
                        output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceAddIPResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.add_i_p,
                ),
                "/fits.api.vm.v1.VMService/MoveIP": Endpoint.unary(
                    method=MethodInfo(
                        name="MoveIP",
                        service_name="fits.api.vm.v1.VMService",
                        input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceMoveIPRequest,
                        output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceMoveIPResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.move_i_p,
                ),
                "/fits.api.vm.v1.VMService/DeleteIP": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteIP",
                        service_name="fits.api.vm.v1.VMService",
                        input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceDeleteIPRequest,
                        output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceDeleteIPResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_i_p,
                ),
                "/fits.api.vm.v1.VMService/ValidateCreate": Endpoint.unary(
                    method=MethodInfo(
                        name="ValidateCreate",
                        service_name="fits.api.vm.v1.VMService",
                        input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateCreateRequest,
                        output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateCreateResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.validate_create,
                ),
                "/fits.api.vm.v1.VMService/ValidateAddDisk": Endpoint.unary(
                    method=MethodInfo(
                        name="ValidateAddDisk",
                        service_name="fits.api.vm.v1.VMService",
                        input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateAddDiskRequest,
                        output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateAddDiskResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.validate_add_disk,
                ),
                "/fits.api.vm.v1.VMService/ValidateUpdateDisk": Endpoint.unary(
                    method=MethodInfo(
                        name="ValidateUpdateDisk",
                        service_name="fits.api.vm.v1.VMService",
                        input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateUpdateDiskRequest,
                        output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateUpdateDiskResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.validate_update_disk,
                ),
                "/fits.api.vm.v1.VMService/ValidateAddIP": Endpoint.unary(
                    method=MethodInfo(
                        name="ValidateAddIP",
                        service_name="fits.api.vm.v1.VMService",
                        input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateAddIPRequest,
                        output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateAddIPResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.validate_add_i_p,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/fits.api.vm.v1.VMService"


class VMServiceClient(ConnectClient):
    async def get(
        self,
        request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceGetRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceGetResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Get",
                service_name="fits.api.vm.v1.VMService",
                input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceGetRequest,
                output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceGetResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def create(
        self,
        request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceCreateRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceCreateResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Create",
                service_name="fits.api.vm.v1.VMService",
                input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceCreateRequest,
                output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceCreateResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def update(
        self,
        request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceUpdateRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceUpdateResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Update",
                service_name="fits.api.vm.v1.VMService",
                input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceUpdateRequest,
                output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceUpdateResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list(
        self,
        request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceListRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceListResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="List",
                service_name="fits.api.vm.v1.VMService",
                input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceListRequest,
                output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceListResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete(
        self,
        request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceDeleteRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceDeleteResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Delete",
                service_name="fits.api.vm.v1.VMService",
                input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceDeleteRequest,
                output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceDeleteResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def add_disk(
        self,
        request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceAddDiskRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceAddDiskResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="AddDisk",
                service_name="fits.api.vm.v1.VMService",
                input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceAddDiskRequest,
                output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceAddDiskResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def update_disk(
        self,
        request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceUpdateDiskRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceUpdateDiskResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateDisk",
                service_name="fits.api.vm.v1.VMService",
                input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceUpdateDiskRequest,
                output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceUpdateDiskResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_disk(
        self,
        request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceDeleteDiskRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceDeleteDiskResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteDisk",
                service_name="fits.api.vm.v1.VMService",
                input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceDeleteDiskRequest,
                output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceDeleteDiskResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def add_i_p(
        self,
        request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceAddIPRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceAddIPResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="AddIP",
                service_name="fits.api.vm.v1.VMService",
                input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceAddIPRequest,
                output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceAddIPResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def move_i_p(
        self,
        request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceMoveIPRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceMoveIPResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="MoveIP",
                service_name="fits.api.vm.v1.VMService",
                input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceMoveIPRequest,
                output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceMoveIPResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_i_p(
        self,
        request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceDeleteIPRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceDeleteIPResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteIP",
                service_name="fits.api.vm.v1.VMService",
                input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceDeleteIPRequest,
                output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceDeleteIPResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def validate_create(
        self,
        request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateCreateRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateCreateResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ValidateCreate",
                service_name="fits.api.vm.v1.VMService",
                input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateCreateRequest,
                output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateCreateResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def validate_add_disk(
        self,
        request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateAddDiskRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateAddDiskResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ValidateAddDisk",
                service_name="fits.api.vm.v1.VMService",
                input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateAddDiskRequest,
                output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateAddDiskResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def validate_update_disk(
        self,
        request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateUpdateDiskRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateUpdateDiskResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ValidateUpdateDisk",
                service_name="fits.api.vm.v1.VMService",
                input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateUpdateDiskRequest,
                output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateUpdateDiskResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def validate_add_i_p(
        self,
        request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateAddIPRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateAddIPResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ValidateAddIP",
                service_name="fits.api.vm.v1.VMService",
                input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateAddIPRequest,
                output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateAddIPResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )





class VMServiceSync(Protocol):
    def get(self, request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceGetRequest, ctx: RequestContext) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceGetResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def create(self, request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceCreateRequest, ctx: RequestContext) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceCreateResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def update(self, request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceUpdateRequest, ctx: RequestContext) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceUpdateResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list(self, request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceListRequest, ctx: RequestContext) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceListResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete(self, request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceDeleteRequest, ctx: RequestContext) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceDeleteResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def add_disk(self, request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceAddDiskRequest, ctx: RequestContext) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceAddDiskResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def update_disk(self, request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceUpdateDiskRequest, ctx: RequestContext) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceUpdateDiskResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete_disk(self, request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceDeleteDiskRequest, ctx: RequestContext) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceDeleteDiskResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def add_i_p(self, request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceAddIPRequest, ctx: RequestContext) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceAddIPResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def move_i_p(self, request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceMoveIPRequest, ctx: RequestContext) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceMoveIPResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete_i_p(self, request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceDeleteIPRequest, ctx: RequestContext) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceDeleteIPResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def validate_create(self, request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateCreateRequest, ctx: RequestContext) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateCreateResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def validate_add_disk(self, request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateAddDiskRequest, ctx: RequestContext) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateAddDiskResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def validate_update_disk(self, request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateUpdateDiskRequest, ctx: RequestContext) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateUpdateDiskResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def validate_add_i_p(self, request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateAddIPRequest, ctx: RequestContext) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateAddIPResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class VMServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: VMServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            endpoints={
                "/fits.api.vm.v1.VMService/Get": EndpointSync.unary(
                    method=MethodInfo(
                        name="Get",
                        service_name="fits.api.vm.v1.VMService",
                        input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceGetRequest,
                        output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceGetResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get,
                ),
                "/fits.api.vm.v1.VMService/Create": EndpointSync.unary(
                    method=MethodInfo(
                        name="Create",
                        service_name="fits.api.vm.v1.VMService",
                        input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceCreateRequest,
                        output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceCreateResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create,
                ),
                "/fits.api.vm.v1.VMService/Update": EndpointSync.unary(
                    method=MethodInfo(
                        name="Update",
                        service_name="fits.api.vm.v1.VMService",
                        input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceUpdateRequest,
                        output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceUpdateResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.update,
                ),
                "/fits.api.vm.v1.VMService/List": EndpointSync.unary(
                    method=MethodInfo(
                        name="List",
                        service_name="fits.api.vm.v1.VMService",
                        input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceListRequest,
                        output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceListResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list,
                ),
                "/fits.api.vm.v1.VMService/Delete": EndpointSync.unary(
                    method=MethodInfo(
                        name="Delete",
                        service_name="fits.api.vm.v1.VMService",
                        input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceDeleteRequest,
                        output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceDeleteResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete,
                ),
                "/fits.api.vm.v1.VMService/AddDisk": EndpointSync.unary(
                    method=MethodInfo(
                        name="AddDisk",
                        service_name="fits.api.vm.v1.VMService",
                        input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceAddDiskRequest,
                        output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceAddDiskResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.add_disk,
                ),
                "/fits.api.vm.v1.VMService/UpdateDisk": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpdateDisk",
                        service_name="fits.api.vm.v1.VMService",
                        input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceUpdateDiskRequest,
                        output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceUpdateDiskResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.update_disk,
                ),
                "/fits.api.vm.v1.VMService/DeleteDisk": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteDisk",
                        service_name="fits.api.vm.v1.VMService",
                        input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceDeleteDiskRequest,
                        output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceDeleteDiskResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_disk,
                ),
                "/fits.api.vm.v1.VMService/AddIP": EndpointSync.unary(
                    method=MethodInfo(
                        name="AddIP",
                        service_name="fits.api.vm.v1.VMService",
                        input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceAddIPRequest,
                        output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceAddIPResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.add_i_p,
                ),
                "/fits.api.vm.v1.VMService/MoveIP": EndpointSync.unary(
                    method=MethodInfo(
                        name="MoveIP",
                        service_name="fits.api.vm.v1.VMService",
                        input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceMoveIPRequest,
                        output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceMoveIPResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.move_i_p,
                ),
                "/fits.api.vm.v1.VMService/DeleteIP": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteIP",
                        service_name="fits.api.vm.v1.VMService",
                        input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceDeleteIPRequest,
                        output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceDeleteIPResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_i_p,
                ),
                "/fits.api.vm.v1.VMService/ValidateCreate": EndpointSync.unary(
                    method=MethodInfo(
                        name="ValidateCreate",
                        service_name="fits.api.vm.v1.VMService",
                        input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateCreateRequest,
                        output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateCreateResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.validate_create,
                ),
                "/fits.api.vm.v1.VMService/ValidateAddDisk": EndpointSync.unary(
                    method=MethodInfo(
                        name="ValidateAddDisk",
                        service_name="fits.api.vm.v1.VMService",
                        input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateAddDiskRequest,
                        output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateAddDiskResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.validate_add_disk,
                ),
                "/fits.api.vm.v1.VMService/ValidateUpdateDisk": EndpointSync.unary(
                    method=MethodInfo(
                        name="ValidateUpdateDisk",
                        service_name="fits.api.vm.v1.VMService",
                        input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateUpdateDiskRequest,
                        output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateUpdateDiskResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.validate_update_disk,
                ),
                "/fits.api.vm.v1.VMService/ValidateAddIP": EndpointSync.unary(
                    method=MethodInfo(
                        name="ValidateAddIP",
                        service_name="fits.api.vm.v1.VMService",
                        input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateAddIPRequest,
                        output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateAddIPResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.validate_add_i_p,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/fits.api.vm.v1.VMService"


class VMServiceClientSync(ConnectClientSync):
    def get(
        self,
        request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceGetRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceGetResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Get",
                service_name="fits.api.vm.v1.VMService",
                input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceGetRequest,
                output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceGetResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def create(
        self,
        request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceCreateRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceCreateResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Create",
                service_name="fits.api.vm.v1.VMService",
                input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceCreateRequest,
                output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceCreateResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def update(
        self,
        request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceUpdateRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceUpdateResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Update",
                service_name="fits.api.vm.v1.VMService",
                input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceUpdateRequest,
                output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceUpdateResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list(
        self,
        request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceListRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceListResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="List",
                service_name="fits.api.vm.v1.VMService",
                input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceListRequest,
                output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceListResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete(
        self,
        request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceDeleteRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceDeleteResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Delete",
                service_name="fits.api.vm.v1.VMService",
                input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceDeleteRequest,
                output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceDeleteResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def add_disk(
        self,
        request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceAddDiskRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceAddDiskResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="AddDisk",
                service_name="fits.api.vm.v1.VMService",
                input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceAddDiskRequest,
                output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceAddDiskResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def update_disk(
        self,
        request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceUpdateDiskRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceUpdateDiskResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateDisk",
                service_name="fits.api.vm.v1.VMService",
                input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceUpdateDiskRequest,
                output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceUpdateDiskResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_disk(
        self,
        request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceDeleteDiskRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceDeleteDiskResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteDisk",
                service_name="fits.api.vm.v1.VMService",
                input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceDeleteDiskRequest,
                output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceDeleteDiskResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def add_i_p(
        self,
        request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceAddIPRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceAddIPResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="AddIP",
                service_name="fits.api.vm.v1.VMService",
                input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceAddIPRequest,
                output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceAddIPResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def move_i_p(
        self,
        request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceMoveIPRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceMoveIPResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="MoveIP",
                service_name="fits.api.vm.v1.VMService",
                input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceMoveIPRequest,
                output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceMoveIPResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_i_p(
        self,
        request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceDeleteIPRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceDeleteIPResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteIP",
                service_name="fits.api.vm.v1.VMService",
                input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceDeleteIPRequest,
                output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceDeleteIPResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def validate_create(
        self,
        request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateCreateRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateCreateResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ValidateCreate",
                service_name="fits.api.vm.v1.VMService",
                input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateCreateRequest,
                output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateCreateResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def validate_add_disk(
        self,
        request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateAddDiskRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateAddDiskResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ValidateAddDisk",
                service_name="fits.api.vm.v1.VMService",
                input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateAddDiskRequest,
                output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateAddDiskResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def validate_update_disk(
        self,
        request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateUpdateDiskRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateUpdateDiskResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ValidateUpdateDisk",
                service_name="fits.api.vm.v1.VMService",
                input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateUpdateDiskRequest,
                output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateUpdateDiskResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def validate_add_i_p(
        self,
        request: fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateAddIPRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateAddIPResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ValidateAddIP",
                service_name="fits.api.vm.v1.VMService",
                input=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateAddIPRequest,
                output=fits_dot_api_dot_vm_dot_v1_dot_vm__pb2.VMServiceValidateAddIPResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


