// @generated by protoc-gen-es v2.14.1 with parameter "target=ts,import_extension=js"
// @generated from file fits/api/mvm/v1/domain.proto (package fits.api.mvm.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../../buf/validate/validate_pb.js";
import { file_fits_api_v1_common } from "../../v1/common_pb.js";
import { file_fits_api_v1_predefined_rules } from "../../v1/predefined_rules_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file fits/api/mvm/v1/domain.proto.
 */
export const file_fits_api_mvm_v1_domain: GenFile = /*@__PURE__*/
  fileDesc("ChxmaXRzL2FwaS9tdm0vdjEvZG9tYWluLnByb3RvEg9maXRzLmFwaS5tdm0udjEiWAoGRG9tYWluEhYKBHV1aWQYASABKAlCCLpIBXIDsAEBEhkKBGZxZG4YAiABKAlCC7pICHIGwLOusQIBEhsKBnRlbmFudBgDIAEoCUILukgIcgbAs66xAgEiNwoYRG9tYWluU2VydmljZUxpc3RSZXF1ZXN0EhsKBnRlbmFudBgBIAEoCUILukgIcgbAs66xAgEiRQoZRG9tYWluU2VydmljZUxpc3RSZXNwb25zZRIoCgdkb21haW5zGAEgAygLMhcuZml0cy5hcGkubXZtLnYxLkRvbWFpbjJ7Cg1Eb21haW5TZXJ2aWNlEmoKBExpc3QSKS5maXRzLmFwaS5tdm0udjEuRG9tYWluU2VydmljZUxpc3RSZXF1ZXN0GiouZml0cy5hcGkubXZtLnYxLkRvbWFpblNlcnZpY2VMaXN0UmVzcG9uc2UiC8LzGAMBAgPg8xgCQrABChNjb20uZml0cy5hcGkubXZtLnYxQgtEb21haW5Qcm90b1ABWi1naXRodWIuY29tL2ZpLXRzL2FwaS9nby9maXRzL2FwaS9tdm0vdjE7bXZtdjGiAgNGQU2qAg9GaXRzLkFwaS5Ndm0uVjHKAg9GaXRzXEFwaVxNdm1cVjHiAhtGaXRzXEFwaVxNdm1cVjFcR1BCTWV0YWRhdGHqAhJGaXRzOjpBcGk6Ok12bTo6VjFiBnByb3RvMw", [file_buf_validate_validate, file_fits_api_v1_common, file_fits_api_v1_predefined_rules]);

/**
 * Domain is a Windows domain a Windows MVM can join.
 *
 * @generated from message fits.api.mvm.v1.Domain
 */
export type Domain = Message<"fits.api.mvm.v1.Domain"> & {
  /**
   * UUID of this domain.
   *
   * @generated from field: string uuid = 1;
   */
  uuid: string;

  /**
   * FQDN of this domain.
   *
   * @generated from field: string fqdn = 2;
   */
  fqdn: string;

  /**
   * Tenant this domain belongs to.
   *
   * @generated from field: string tenant = 3;
   */
  tenant: string;
};

/**
 * Describes the message fits.api.mvm.v1.Domain.
 * Use `create(DomainSchema)` to create a new message.
 */
export const DomainSchema: GenMessage<Domain> = /*@__PURE__*/
  messageDesc(file_fits_api_mvm_v1_domain, 0);

/**
 * DomainServiceListRequest is the request payload for a domain list request.
 *
 * @generated from message fits.api.mvm.v1.DomainServiceListRequest
 */
export type DomainServiceListRequest = Message<"fits.api.mvm.v1.DomainServiceListRequest"> & {
  /**
   * Tenant to list available domains for.
   *
   * @generated from field: string tenant = 1;
   */
  tenant: string;
};

/**
 * Describes the message fits.api.mvm.v1.DomainServiceListRequest.
 * Use `create(DomainServiceListRequestSchema)` to create a new message.
 */
export const DomainServiceListRequestSchema: GenMessage<DomainServiceListRequest> = /*@__PURE__*/
  messageDesc(file_fits_api_mvm_v1_domain, 1);

/**
 * DomainServiceListResponse is the response payload for a domain list request.
 *
 * @generated from message fits.api.mvm.v1.DomainServiceListResponse
 */
export type DomainServiceListResponse = Message<"fits.api.mvm.v1.DomainServiceListResponse"> & {
  /**
   * The available domains.
   *
   * @generated from field: repeated fits.api.mvm.v1.Domain domains = 1;
   */
  domains: Domain[];
};

/**
 * Describes the message fits.api.mvm.v1.DomainServiceListResponse.
 * Use `create(DomainServiceListResponseSchema)` to create a new message.
 */
export const DomainServiceListResponseSchema: GenMessage<DomainServiceListResponse> = /*@__PURE__*/
  messageDesc(file_fits_api_mvm_v1_domain, 2);

/**
 * DomainService lists Windows domains available for managed VM (MVM) instances.
 *
 * @generated from service fits.api.mvm.v1.DomainService
 */
export const DomainService: GenService<{
  /**
   * Returns a list of all Windows domains available for a tenant.
   *
   * @generated from rpc fits.api.mvm.v1.DomainService.List
   */
  list: {
    methodKind: "unary";
    input: typeof DomainServiceListRequestSchema;
    output: typeof DomainServiceListResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_fits_api_mvm_v1_domain, 0);

