// @generated by protoc-gen-es v2.14.1 with parameter "target=ts"
// @generated from file fits/api/mvm/v1/vlan.proto (package fits.api.mvm.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../../buf/validate/validate_pb";
import { file_fits_api_v1_common } from "../../v1/common_pb";
import { file_fits_api_v1_predefined_rules } from "../../v1/predefined_rules_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file fits/api/mvm/v1/vlan.proto.
 */
export const file_fits_api_mvm_v1_vlan: GenFile = /*@__PURE__*/
  fileDesc("ChpmaXRzL2FwaS9tdm0vdjEvdmxhbi5wcm90bxIPZml0cy5hcGkubXZtLnYxIroCCgRWTEFOEhYKBHV1aWQYASABKAlCCLpIBXIDsAEBEgoKAmlkGAIgASgFEiEKDHN1Ym5ldF90aXRsZRgDIAEoCUILukgIcgbAs66xAgESDgoGc3VibmV0GAQgASgJEhIKCnN1Ym5ldG1hc2sYBSABKAkSDwoHZ2F0ZXdheRgGIAEoCRIWCg5pcF9yYW5nZV9zdGFydBgHIAEoCRIUCgxpcF9yYW5nZV9lbmQYCCABKAkSEAoIdXNlX2RoY3AYCSABKAgSJAoNbG9jYXRpb25fdXVpZBgNIAEoCUIIukgFcgOwAQFIAIgBARIhCg9zdGFnZV90eXBlX3V1aWQYDiABKAlCCLpIBXIDsAEBEhsKBnRlbmFudBgPIAEoCUILukgIcgbAs66xAgFCEAoOX2xvY2F0aW9uX3V1aWQiNQoWVkxBTlNlcnZpY2VMaXN0UmVxdWVzdBIbCgZ0ZW5hbnQYASABKAlCC7pICHIGwLOusQIBIj8KF1ZMQU5TZXJ2aWNlTGlzdFJlc3BvbnNlEiQKBXZsYW5zGAEgAygLMhUuZml0cy5hcGkubXZtLnYxLlZMQU4ydQoLVkxBTlNlcnZpY2USZgoETGlzdBInLmZpdHMuYXBpLm12bS52MS5WTEFOU2VydmljZUxpc3RSZXF1ZXN0GiguZml0cy5hcGkubXZtLnYxLlZMQU5TZXJ2aWNlTGlzdFJlc3BvbnNlIgvK8xgDAQID4PMYAkKuAQoTY29tLmZpdHMuYXBpLm12bS52MUIJVmxhblByb3RvUAFaLWdpdGh1Yi5jb20vZmktdHMvYXBpL2dvL2ZpdHMvYXBpL212bS92MTttdm12MaICA0ZBTaoCD0ZpdHMuQXBpLk12bS5WMcoCD0ZpdHNcQXBpXE12bVxWMeICG0ZpdHNcQXBpXE12bVxWMVxHUEJNZXRhZGF0YeoCEkZpdHM6OkFwaTo6TXZtOjpWMWIGcHJvdG8z", [file_buf_validate_validate, file_fits_api_v1_common, file_fits_api_v1_predefined_rules]);

/**
 * VLAN is a VLAN that a MVM can be connected to.
 *
 * @generated from message fits.api.mvm.v1.VLAN
 */
export type VLAN = Message<"fits.api.mvm.v1.VLAN"> & {
  /**
   * Uuid of this VLAN
   *
   * @generated from field: string uuid = 1;
   */
  uuid: string;

  /**
   * Id of this VLAN
   *
   * @generated from field: int32 id = 2;
   */
  id: number;

  /**
   * Title of the subnet this VLAN belongs to
   *
   * @generated from field: string subnet_title = 3;
   */
  subnetTitle: string;

  /**
   * CIDR of the subnet this VLAN belongs to
   *
   * @generated from field: string subnet = 4;
   */
  subnet: string;

  /**
   * Subnetmask of this VLAN
   *
   * @generated from field: string subnetmask = 5;
   */
  subnetmask: string;

  /**
   * Gateway of this VLAN
   *
   * @generated from field: string gateway = 6;
   */
  gateway: string;

  /**
   * Start of the usable IP range of this VLAN
   *
   * @generated from field: string ip_range_start = 7;
   */
  ipRangeStart: string;

  /**
   * End of the usable IP range of this VLAN
   *
   * @generated from field: string ip_range_end = 8;
   */
  ipRangeEnd: string;

  /**
   * Whether DHCP is used on this VLAN
   *
   * @generated from field: bool use_dhcp = 9;
   */
  useDhcp: boolean;

  /**
   * TODO instead of the pod title, could we have the location_uuid?
   *
   * @generated from field: optional string location_uuid = 13;
   */
  locationUuid?: string | undefined;

  /**
   * Uuid of the stage type of this VLAN
   *
   * @generated from field: string stage_type_uuid = 14;
   */
  stageTypeUuid: string;

  /**
   * Tenant this VLAN belongs to.
   *
   * @generated from field: string tenant = 15;
   */
  tenant: string;
};

/**
 * Describes the message fits.api.mvm.v1.VLAN.
 * Use `create(VLANSchema)` to create a new message.
 */
export const VLANSchema: GenMessage<VLAN> = /*@__PURE__*/
  messageDesc(file_fits_api_mvm_v1_vlan, 0);

/**
 * VLANServiceListRequest is the request payload for a VLAN list request.
 *
 * @generated from message fits.api.mvm.v1.VLANServiceListRequest
 */
export type VLANServiceListRequest = Message<"fits.api.mvm.v1.VLANServiceListRequest"> & {
  /**
   * Tenant to list available VLANs for
   *
   * @generated from field: string tenant = 1;
   */
  tenant: string;
};

/**
 * Describes the message fits.api.mvm.v1.VLANServiceListRequest.
 * Use `create(VLANServiceListRequestSchema)` to create a new message.
 */
export const VLANServiceListRequestSchema: GenMessage<VLANServiceListRequest> = /*@__PURE__*/
  messageDesc(file_fits_api_mvm_v1_vlan, 1);

/**
 * VLANServiceListResponse is the response payload for a VLAN list request
 *
 * @generated from message fits.api.mvm.v1.VLANServiceListResponse
 */
export type VLANServiceListResponse = Message<"fits.api.mvm.v1.VLANServiceListResponse"> & {
  /**
   * The available VLANs
   *
   * @generated from field: repeated fits.api.mvm.v1.VLAN vlans = 1;
   */
  vlans: VLAN[];
};

/**
 * Describes the message fits.api.mvm.v1.VLANServiceListResponse.
 * Use `create(VLANServiceListResponseSchema)` to create a new message.
 */
export const VLANServiceListResponseSchema: GenMessage<VLANServiceListResponse> = /*@__PURE__*/
  messageDesc(file_fits_api_mvm_v1_vlan, 2);

/**
 * VLANService lists VLANs available for managed VM (MVM) instances.
 *
 * @generated from service fits.api.mvm.v1.VLANService
 */
export const VLANService: GenService<{
  /**
   * Returns a list of all VLANs available for a tenant.
   *
   * @generated from rpc fits.api.mvm.v1.VLANService.List
   */
  list: {
    methodKind: "unary";
    input: typeof VLANServiceListRequestSchema;
    output: typeof VLANServiceListResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_fits_api_mvm_v1_vlan, 0);

