// @generated by protoc-gen-es v2.14.1 with parameter "target=ts,import_extension=js"
// @generated from file fits/api/mvm/v1/vlan.proto (package fits.api.mvm.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../../buf/validate/validate_pb.js";
import { file_fits_api_v1_common } from "../../v1/common_pb.js";
import { file_fits_api_v1_predefined_rules } from "../../v1/predefined_rules_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file fits/api/mvm/v1/vlan.proto.
 */
export const file_fits_api_mvm_v1_vlan: GenFile = /*@__PURE__*/
  fileDesc("ChpmaXRzL2FwaS9tdm0vdjEvdmxhbi5wcm90bxIPZml0cy5hcGkubXZtLnYxIuYBCgRWTEFOEhYKBHV1aWQYASABKAlCCLpIBXIDsAEBEg8KB3ZsYW5faWQYAiABKAUSIQoMc3VibmV0X3RpdGxlGAMgASgJQgu6SAhyBsCzrrECARIgCgtzdWJuZXRfY2lkchgEIAEoCUILukgIcgaAtK6xAgESHwoNbG9jYXRpb25fdXVpZBgFIAEoCUIIukgFcgOwAQESGwoGdGVuYW50GAYgASgJQgu6SAhyBsCzrrECARIiCgtkb21haW5fdXVpZBgHIAEoCUIIukgFcgOwAQFIAIgBAUIOCgxfZG9tYWluX3V1aWQiigEKFlZMQU5TZXJ2aWNlTGlzdFJlcXVlc3QSGwoGdGVuYW50GAEgASgJQgu6SAhyBsCzrrECARIfCg1sb2NhdGlvbl91dWlkGAIgASgJQgi6SAVyA7ABARIiCgtkb21haW5fdXVpZBgDIAEoCUIIukgFcgOwAQFIAIgBAUIOCgxfZG9tYWluX3V1aWQiPwoXVkxBTlNlcnZpY2VMaXN0UmVzcG9uc2USJAoFdmxhbnMYASADKAsyFS5maXRzLmFwaS5tdm0udjEuVkxBTjJ1CgtWTEFOU2VydmljZRJmCgRMaXN0EicuZml0cy5hcGkubXZtLnYxLlZMQU5TZXJ2aWNlTGlzdFJlcXVlc3QaKC5maXRzLmFwaS5tdm0udjEuVkxBTlNlcnZpY2VMaXN0UmVzcG9uc2UiC8LzGAMBAgPg8xgCQq4BChNjb20uZml0cy5hcGkubXZtLnYxQglWbGFuUHJvdG9QAVotZ2l0aHViLmNvbS9maS10cy9hcGkvZ28vZml0cy9hcGkvbXZtL3YxO212bXYxogIDRkFNqgIPRml0cy5BcGkuTXZtLlYxygIPRml0c1xBcGlcTXZtXFYx4gIbRml0c1xBcGlcTXZtXFYxXEdQQk1ldGFkYXRh6gISRml0czo6QXBpOjpNdm06OlYxYgZwcm90bzM", [file_buf_validate_validate, file_fits_api_v1_common, file_fits_api_v1_predefined_rules]);

/**
 * VLAN is a VLAN that a MVM can be connected to.
 *
 * @generated from message fits.api.mvm.v1.VLAN
 */
export type VLAN = Message<"fits.api.mvm.v1.VLAN"> & {
  /**
   * UUID of this VLAN.
   *
   * @generated from field: string uuid = 1;
   */
  uuid: string;

  /**
   * ID of this VLAN. The actual VLAN ID a network interface is attached to.
   *
   * @generated from field: int32 vlan_id = 2;
   */
  vlanId: number;

  /**
   * Title of the subnet this VLAN belongs to, including the stage type, e.g. "pod01-vlan2001 (Production)".
   *
   * @generated from field: string subnet_title = 3;
   */
  subnetTitle: string;

  /**
   * CIDR of the subnet this VLAN belongs to.
   *
   * @generated from field: string subnet_cidr = 4;
   */
  subnetCidr: string;

  /**
   * UUID of the location this VLAN belongs to. This is actually the FCE datacenter ID.
   *
   * @generated from field: string location_uuid = 5;
   */
  locationUuid: string;

  /**
   * Tenant this VLAN belongs to.
   *
   * @generated from field: string tenant = 6;
   */
  tenant: string;

  /**
   * UUID of the Windows domain this VLAN is associated with. Only set for Windows.
   *
   * @generated from field: optional string domain_uuid = 7;
   */
  domainUuid?: string | undefined;
};

/**
 * Describes the message fits.api.mvm.v1.VLAN.
 * Use `create(VLANSchema)` to create a new message.
 */
export const VLANSchema: GenMessage<VLAN> = /*@__PURE__*/
  messageDesc(file_fits_api_mvm_v1_vlan, 0);

/**
 * VLANServiceListRequest is the request payload for a VLAN list request.
 *
 * @generated from message fits.api.mvm.v1.VLANServiceListRequest
 */
export type VLANServiceListRequest = Message<"fits.api.mvm.v1.VLANServiceListRequest"> & {
  /**
   * Tenant to list available VLANs for (the tenant login).
   *
   * @generated from field: string tenant = 1;
   */
  tenant: string;

  /**
   * Filter the listed VLANs by location (the FCE datacenter ID).
   *
   * @generated from field: string location_uuid = 2;
   */
  locationUuid: string;

  /**
   * Filter the listed VLANs by the Windows domain they are associated with.
   *
   * @generated from field: optional string domain_uuid = 3;
   */
  domainUuid?: string | undefined;
};

/**
 * Describes the message fits.api.mvm.v1.VLANServiceListRequest.
 * Use `create(VLANServiceListRequestSchema)` to create a new message.
 */
export const VLANServiceListRequestSchema: GenMessage<VLANServiceListRequest> = /*@__PURE__*/
  messageDesc(file_fits_api_mvm_v1_vlan, 1);

/**
 * VLANServiceListResponse is the response payload for a VLAN list request.
 *
 * @generated from message fits.api.mvm.v1.VLANServiceListResponse
 */
export type VLANServiceListResponse = Message<"fits.api.mvm.v1.VLANServiceListResponse"> & {
  /**
   * The available VLANs.
   *
   * @generated from field: repeated fits.api.mvm.v1.VLAN vlans = 1;
   */
  vlans: VLAN[];
};

/**
 * Describes the message fits.api.mvm.v1.VLANServiceListResponse.
 * Use `create(VLANServiceListResponseSchema)` to create a new message.
 */
export const VLANServiceListResponseSchema: GenMessage<VLANServiceListResponse> = /*@__PURE__*/
  messageDesc(file_fits_api_mvm_v1_vlan, 2);

/**
 * VLANService lists VLANs available for managed VM (MVM) instances.
 *
 * @generated from service fits.api.mvm.v1.VLANService
 */
export const VLANService: GenService<{
  /**
   * Returns a list of all VLANs available for a tenant.
   *
   * @generated from rpc fits.api.mvm.v1.VLANService.List
   */
  list: {
    methodKind: "unary";
    input: typeof VLANServiceListRequestSchema;
    output: typeof VLANServiceListResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_fits_api_mvm_v1_vlan, 0);

