// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: fits/api/v1/common.proto

package apiv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TenantRole specifies what role a logged in user needs to call this tenant scoped service
type TenantRole int32

const (
	// TENANT_ROLE_UNSPECIFIED is not specified
	TenantRole_TENANT_ROLE_UNSPECIFIED TenantRole = 0
	// TENANT_ROLE_OWNER the logged in user needs at least owner role to call this method
	TenantRole_TENANT_ROLE_OWNER TenantRole = 1
	// TENANT_ROLE_EDITOR the logged in user needs at least editor role to call this method
	TenantRole_TENANT_ROLE_EDITOR TenantRole = 2
	// TENANT_ROLE_VIEWER the logged in user needs at least viewer role to call this method
	TenantRole_TENANT_ROLE_VIEWER TenantRole = 3
	// TENANT_ROLE_GUEST the logged in user needs at least guest role to call this method
	// The guest role is assumed by users who are invited to a tenant's project without them
	// having a direct membership within the tenant.
	TenantRole_TENANT_ROLE_GUEST TenantRole = 4
)

// Enum value maps for TenantRole.
var (
	TenantRole_name = map[int32]string{
		0: "TENANT_ROLE_UNSPECIFIED",
		1: "TENANT_ROLE_OWNER",
		2: "TENANT_ROLE_EDITOR",
		3: "TENANT_ROLE_VIEWER",
		4: "TENANT_ROLE_GUEST",
	}
	TenantRole_value = map[string]int32{
		"TENANT_ROLE_UNSPECIFIED": 0,
		"TENANT_ROLE_OWNER":       1,
		"TENANT_ROLE_EDITOR":      2,
		"TENANT_ROLE_VIEWER":      3,
		"TENANT_ROLE_GUEST":       4,
	}
)

func (x TenantRole) Enum() *TenantRole {
	p := new(TenantRole)
	*p = x
	return p
}

func (x TenantRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TenantRole) Descriptor() protoreflect.EnumDescriptor {
	return file_fits_api_v1_common_proto_enumTypes[0].Descriptor()
}

func (TenantRole) Type() protoreflect.EnumType {
	return &file_fits_api_v1_common_proto_enumTypes[0]
}

func (x TenantRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TenantRole.Descriptor instead.
func (TenantRole) EnumDescriptor() ([]byte, []int) {
	return file_fits_api_v1_common_proto_rawDescGZIP(), []int{0}
}

// ProjectRole specifies what role a logged in user needs to call this project scoped service
type ProjectRole int32

const (
	// PROJECT_ROLE_UNSPECIFIED is not specified
	ProjectRole_PROJECT_ROLE_UNSPECIFIED ProjectRole = 0
	// PROJECT_ROLE_OWNER the logged in user needs at least owner role to call this method
	ProjectRole_PROJECT_ROLE_OWNER ProjectRole = 1
	// PROJECT_ROLE_EDITOR the logged in user needs at least editor role to call this method
	ProjectRole_PROJECT_ROLE_EDITOR ProjectRole = 2
	// PROJECT_ROLE_VIEWER the logged in user needs at least viewer role to call this method
	ProjectRole_PROJECT_ROLE_VIEWER ProjectRole = 3
)

// Enum value maps for ProjectRole.
var (
	ProjectRole_name = map[int32]string{
		0: "PROJECT_ROLE_UNSPECIFIED",
		1: "PROJECT_ROLE_OWNER",
		2: "PROJECT_ROLE_EDITOR",
		3: "PROJECT_ROLE_VIEWER",
	}
	ProjectRole_value = map[string]int32{
		"PROJECT_ROLE_UNSPECIFIED": 0,
		"PROJECT_ROLE_OWNER":       1,
		"PROJECT_ROLE_EDITOR":      2,
		"PROJECT_ROLE_VIEWER":      3,
	}
)

func (x ProjectRole) Enum() *ProjectRole {
	p := new(ProjectRole)
	*p = x
	return p
}

func (x ProjectRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProjectRole) Descriptor() protoreflect.EnumDescriptor {
	return file_fits_api_v1_common_proto_enumTypes[1].Descriptor()
}

func (ProjectRole) Type() protoreflect.EnumType {
	return &file_fits_api_v1_common_proto_enumTypes[1]
}

func (x ProjectRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProjectRole.Descriptor instead.
func (ProjectRole) EnumDescriptor() ([]byte, []int) {
	return file_fits_api_v1_common_proto_rawDescGZIP(), []int{1}
}

// AdminRole specifies what role a logged in user needs to call this admin service
type AdminRole int32

const (
	// ADMIN_ROLE_UNSPECIFIED is not specified
	AdminRole_ADMIN_ROLE_UNSPECIFIED AdminRole = 0
	// ADMIN_ROLE_EDITOR the logged in user needs at least editor role to call this method
	AdminRole_ADMIN_ROLE_EDITOR AdminRole = 1
	// ADMIN_ROLE_VIEWER the logged in user needs at least viewer role to call this method
	AdminRole_ADMIN_ROLE_VIEWER AdminRole = 2
)

// Enum value maps for AdminRole.
var (
	AdminRole_name = map[int32]string{
		0: "ADMIN_ROLE_UNSPECIFIED",
		1: "ADMIN_ROLE_EDITOR",
		2: "ADMIN_ROLE_VIEWER",
	}
	AdminRole_value = map[string]int32{
		"ADMIN_ROLE_UNSPECIFIED": 0,
		"ADMIN_ROLE_EDITOR":      1,
		"ADMIN_ROLE_VIEWER":      2,
	}
)

func (x AdminRole) Enum() *AdminRole {
	p := new(AdminRole)
	*p = x
	return p
}

func (x AdminRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdminRole) Descriptor() protoreflect.EnumDescriptor {
	return file_fits_api_v1_common_proto_enumTypes[2].Descriptor()
}

func (AdminRole) Type() protoreflect.EnumType {
	return &file_fits_api_v1_common_proto_enumTypes[2]
}

func (x AdminRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdminRole.Descriptor instead.
func (AdminRole) EnumDescriptor() ([]byte, []int) {
	return file_fits_api_v1_common_proto_rawDescGZIP(), []int{2}
}

// InfraRole specifies what role a microservice needs to call this infra service
type InfraRole int32

const (
	// INFRA_ROLE_UNSPECIFIED is not specified
	InfraRole_INFRA_ROLE_UNSPECIFIED InfraRole = 0
	// INFRA_ROLE_EDITOR a microservice needs at least editor role to call this method
	InfraRole_INFRA_ROLE_EDITOR InfraRole = 1
	// INFRA_ROLE_VIEWER a microservice needs at least viewer role to call this method
	InfraRole_INFRA_ROLE_VIEWER InfraRole = 2
)

// Enum value maps for InfraRole.
var (
	InfraRole_name = map[int32]string{
		0: "INFRA_ROLE_UNSPECIFIED",
		1: "INFRA_ROLE_EDITOR",
		2: "INFRA_ROLE_VIEWER",
	}
	InfraRole_value = map[string]int32{
		"INFRA_ROLE_UNSPECIFIED": 0,
		"INFRA_ROLE_EDITOR":      1,
		"INFRA_ROLE_VIEWER":      2,
	}
)

func (x InfraRole) Enum() *InfraRole {
	p := new(InfraRole)
	*p = x
	return p
}

func (x InfraRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InfraRole) Descriptor() protoreflect.EnumDescriptor {
	return file_fits_api_v1_common_proto_enumTypes[3].Descriptor()
}

func (InfraRole) Type() protoreflect.EnumType {
	return &file_fits_api_v1_common_proto_enumTypes[3]
}

func (x InfraRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InfraRole.Descriptor instead.
func (InfraRole) EnumDescriptor() ([]byte, []int) {
	return file_fits_api_v1_common_proto_rawDescGZIP(), []int{3}
}

// MachineRole specifies what role a microservice needs to call this machine service
type MachineRole int32

const (
	// MACHINE_ROLE_UNSPECIFIED is not specified
	MachineRole_MACHINE_ROLE_UNSPECIFIED MachineRole = 0
	// MACHINE_ROLE_EDITOR a microservice needs at least editor role to call this method
	MachineRole_MACHINE_ROLE_EDITOR MachineRole = 1
	// MACHINE_ROLE_VIEWER a microservice needs at least viewer role to call this method
	MachineRole_MACHINE_ROLE_VIEWER MachineRole = 2
)

// Enum value maps for MachineRole.
var (
	MachineRole_name = map[int32]string{
		0: "MACHINE_ROLE_UNSPECIFIED",
		1: "MACHINE_ROLE_EDITOR",
		2: "MACHINE_ROLE_VIEWER",
	}
	MachineRole_value = map[string]int32{
		"MACHINE_ROLE_UNSPECIFIED": 0,
		"MACHINE_ROLE_EDITOR":      1,
		"MACHINE_ROLE_VIEWER":      2,
	}
)

func (x MachineRole) Enum() *MachineRole {
	p := new(MachineRole)
	*p = x
	return p
}

func (x MachineRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MachineRole) Descriptor() protoreflect.EnumDescriptor {
	return file_fits_api_v1_common_proto_enumTypes[4].Descriptor()
}

func (MachineRole) Type() protoreflect.EnumType {
	return &file_fits_api_v1_common_proto_enumTypes[4]
}

func (x MachineRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MachineRole.Descriptor instead.
func (MachineRole) EnumDescriptor() ([]byte, []int) {
	return file_fits_api_v1_common_proto_rawDescGZIP(), []int{4}
}

// Visibility of a method
type Visibility int32

const (
	// VISIBILITY_UNSPECIFIED is not defined
	Visibility_VISIBILITY_UNSPECIFIED Visibility = 0
	// VISIBILITY_PUBLIC specifies that this service is accessible without authentication
	Visibility_VISIBILITY_PUBLIC Visibility = 1
	// VISIBILITY_SELF enable call this endpoint from the authenticated user only
	Visibility_VISIBILITY_SELF Visibility = 2
)

// Enum value maps for Visibility.
var (
	Visibility_name = map[int32]string{
		0: "VISIBILITY_UNSPECIFIED",
		1: "VISIBILITY_PUBLIC",
		2: "VISIBILITY_SELF",
	}
	Visibility_value = map[string]int32{
		"VISIBILITY_UNSPECIFIED": 0,
		"VISIBILITY_PUBLIC":      1,
		"VISIBILITY_SELF":        2,
	}
)

func (x Visibility) Enum() *Visibility {
	p := new(Visibility)
	*p = x
	return p
}

func (x Visibility) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Visibility) Descriptor() protoreflect.EnumDescriptor {
	return file_fits_api_v1_common_proto_enumTypes[5].Descriptor()
}

func (Visibility) Type() protoreflect.EnumType {
	return &file_fits_api_v1_common_proto_enumTypes[5]
}

func (x Visibility) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Visibility.Descriptor instead.
func (Visibility) EnumDescriptor() ([]byte, []int) {
	return file_fits_api_v1_common_proto_rawDescGZIP(), []int{5}
}

// Auditing option specified per service method
// by default all service methods are included
// add the auditing option if you want to exclude a method in auditing
type Auditing int32

const (
	// AUDITING_UNSPECIFIED is not specified
	Auditing_AUDITING_UNSPECIFIED Auditing = 0
	// AUDITING_INCLUDED if a method is annotated with this, all calls are audited
	Auditing_AUDITING_INCLUDED Auditing = 1
	// AUDITING_EXCLUDED if a method is annotated with this, no calls are audited
	Auditing_AUDITING_EXCLUDED Auditing = 2
)

// Enum value maps for Auditing.
var (
	Auditing_name = map[int32]string{
		0: "AUDITING_UNSPECIFIED",
		1: "AUDITING_INCLUDED",
		2: "AUDITING_EXCLUDED",
	}
	Auditing_value = map[string]int32{
		"AUDITING_UNSPECIFIED": 0,
		"AUDITING_INCLUDED":    1,
		"AUDITING_EXCLUDED":    2,
	}
)

func (x Auditing) Enum() *Auditing {
	p := new(Auditing)
	*p = x
	return p
}

func (x Auditing) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Auditing) Descriptor() protoreflect.EnumDescriptor {
	return file_fits_api_v1_common_proto_enumTypes[6].Descriptor()
}

func (Auditing) Type() protoreflect.EnumType {
	return &file_fits_api_v1_common_proto_enumTypes[6]
}

func (x Auditing) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Auditing.Descriptor instead.
func (Auditing) EnumDescriptor() ([]byte, []int) {
	return file_fits_api_v1_common_proto_rawDescGZIP(), []int{6}
}

// OptimisticLockingStrategy defines how optimistic locking should be handled.
// It defaults to client side, which requires the UpdatedAt timestamp to be provided
type OptimisticLockingStrategy int32

const (
	// OPTIMISTIC_LOCKING_STRATEGY_UNSPECIFIED same as client side
	OptimisticLockingStrategy_OPTIMISTIC_LOCKING_STRATEGY_UNSPECIFIED OptimisticLockingStrategy = 0
	// OPTIMISTIC_LOCKING_STRATEGY_CLIENT requires UpdatedAt to be specified
	OptimisticLockingStrategy_OPTIMISTIC_LOCKING_STRATEGY_CLIENT OptimisticLockingStrategy = 1
	// OPTIMISTIC_LOCKING_STRATEGY_SERVER allows to omit UpdatedAt
	// and fetches the most recent entity before updating with the given values with the update request
	OptimisticLockingStrategy_OPTIMISTIC_LOCKING_STRATEGY_SERVER OptimisticLockingStrategy = 2
)

// Enum value maps for OptimisticLockingStrategy.
var (
	OptimisticLockingStrategy_name = map[int32]string{
		0: "OPTIMISTIC_LOCKING_STRATEGY_UNSPECIFIED",
		1: "OPTIMISTIC_LOCKING_STRATEGY_CLIENT",
		2: "OPTIMISTIC_LOCKING_STRATEGY_SERVER",
	}
	OptimisticLockingStrategy_value = map[string]int32{
		"OPTIMISTIC_LOCKING_STRATEGY_UNSPECIFIED": 0,
		"OPTIMISTIC_LOCKING_STRATEGY_CLIENT":      1,
		"OPTIMISTIC_LOCKING_STRATEGY_SERVER":      2,
	}
)

func (x OptimisticLockingStrategy) Enum() *OptimisticLockingStrategy {
	p := new(OptimisticLockingStrategy)
	*p = x
	return p
}

func (x OptimisticLockingStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OptimisticLockingStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_fits_api_v1_common_proto_enumTypes[7].Descriptor()
}

func (OptimisticLockingStrategy) Type() protoreflect.EnumType {
	return &file_fits_api_v1_common_proto_enumTypes[7]
}

func (x OptimisticLockingStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OptimisticLockingStrategy.Descriptor instead.
func (OptimisticLockingStrategy) EnumDescriptor() ([]byte, []int) {
	return file_fits_api_v1_common_proto_rawDescGZIP(), []int{7}
}

// Paging defines paging for methods with a lot of results
type Paging struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Page is used for pagination, if unset only the first page is returned,
	// the list response contains then the page number for the next page.
	Page *uint64 `protobuf:"varint,1,opt,name=page,proto3,oneof" json:"page,omitempty"`
	// Count is the number of results returned per page, if not given server side defaults apply
	Count         *uint64 `protobuf:"varint,2,opt,name=count,proto3,oneof" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Paging) Reset() {
	*x = Paging{}
	mi := &file_fits_api_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Paging) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Paging) ProtoMessage() {}

func (x *Paging) ProtoReflect() protoreflect.Message {
	mi := &file_fits_api_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Paging.ProtoReflect.Descriptor instead.
func (*Paging) Descriptor() ([]byte, []int) {
	return file_fits_api_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *Paging) GetPage() uint64 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *Paging) GetCount() uint64 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

// Labels define additional information to a entity
type Labels struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Labels consists labels
	Labels        map[string]string `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Labels) Reset() {
	*x = Labels{}
	mi := &file_fits_api_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Labels) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Labels) ProtoMessage() {}

func (x *Labels) ProtoReflect() protoreflect.Message {
	mi := &file_fits_api_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Labels.ProtoReflect.Descriptor instead.
func (*Labels) Descriptor() ([]byte, []int) {
	return file_fits_api_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *Labels) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// Meta of a message
type Meta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tags on this entity
	Labels *Labels `protobuf:"bytes,1,opt,name=labels,proto3,oneof" json:"labels,omitempty"`
	// CreatedAt is the date when this entity was created
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// UpdatedAt is the date when this entity was updated
	// must be part of the update request to ensure optimistic locking
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Generation identifies how often this entity was modified since creation.
	Generation    uint64 `protobuf:"varint,4,opt,name=generation,proto3" json:"generation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Meta) Reset() {
	*x = Meta{}
	mi := &file_fits_api_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meta) ProtoMessage() {}

func (x *Meta) ProtoReflect() protoreflect.Message {
	mi := &file_fits_api_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meta.ProtoReflect.Descriptor instead.
func (*Meta) Descriptor() ([]byte, []int) {
	return file_fits_api_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *Meta) GetLabels() *Labels {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Meta) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Meta) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Meta) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

// UpdateLabels is a message to update labels
type UpdateLabels struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Update labels. New ones will be added, existing ones overwritten
	Update *Labels `protobuf:"bytes,1,opt,name=update,proto3" json:"update,omitempty"`
	// Remove labels by key
	Remove        []string `protobuf:"bytes,2,rep,name=remove,proto3" json:"remove,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLabels) Reset() {
	*x = UpdateLabels{}
	mi := &file_fits_api_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLabels) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLabels) ProtoMessage() {}

func (x *UpdateLabels) ProtoReflect() protoreflect.Message {
	mi := &file_fits_api_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLabels.ProtoReflect.Descriptor instead.
func (*UpdateLabels) Descriptor() ([]byte, []int) {
	return file_fits_api_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateLabels) GetUpdate() *Labels {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *UpdateLabels) GetRemove() []string {
	if x != nil {
		return x.Remove
	}
	return nil
}

// UpdateMeta must be provided with every UpdateRequest to define how optimistic locking should be handled
type UpdateMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UpdatedAt is the date when this entity was updated
	// must be part of the update request to ensure optimistic locking
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// LockingStrategy to be used for this update request
	LockingStrategy OptimisticLockingStrategy `protobuf:"varint,2,opt,name=locking_strategy,json=lockingStrategy,proto3,enum=fits.api.v1.OptimisticLockingStrategy" json:"locking_strategy,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateMeta) Reset() {
	*x = UpdateMeta{}
	mi := &file_fits_api_v1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMeta) ProtoMessage() {}

func (x *UpdateMeta) ProtoReflect() protoreflect.Message {
	mi := &file_fits_api_v1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMeta.ProtoReflect.Descriptor instead.
func (*UpdateMeta) Descriptor() ([]byte, []int) {
	return file_fits_api_v1_common_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateMeta) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *UpdateMeta) GetLockingStrategy() OptimisticLockingStrategy {
	if x != nil {
		return x.LockingStrategy
	}
	return OptimisticLockingStrategy_OPTIMISTIC_LOCKING_STRATEGY_UNSPECIFIED
}

var file_fits_api_v1_common_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: ([]TenantRole)(nil),
		Field:         51000,
		Name:          "fits.api.v1.tenant_roles",
		Tag:           "varint,51000,rep,packed,name=tenant_roles,enum=fits.api.v1.TenantRole",
		Filename:      "fits/api/v1/common.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: ([]ProjectRole)(nil),
		Field:         51001,
		Name:          "fits.api.v1.project_roles",
		Tag:           "varint,51001,rep,packed,name=project_roles,enum=fits.api.v1.ProjectRole",
		Filename:      "fits/api/v1/common.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: ([]AdminRole)(nil),
		Field:         51002,
		Name:          "fits.api.v1.admin_roles",
		Tag:           "varint,51002,rep,packed,name=admin_roles,enum=fits.api.v1.AdminRole",
		Filename:      "fits/api/v1/common.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*Visibility)(nil),
		Field:         51003,
		Name:          "fits.api.v1.visibility",
		Tag:           "varint,51003,opt,name=visibility,enum=fits.api.v1.Visibility",
		Filename:      "fits/api/v1/common.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*Auditing)(nil),
		Field:         51004,
		Name:          "fits.api.v1.auditing",
		Tag:           "varint,51004,opt,name=auditing,enum=fits.api.v1.Auditing",
		Filename:      "fits/api/v1/common.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         52000,
		Name:          "fits.api.v1.enum_string_value",
		Tag:           "bytes,52000,opt,name=enum_string_value",
		Filename:      "fits/api/v1/common.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// TenantRoles are used to define which tenant role a logged in user must provide to call this method
	//
	// repeated fits.api.v1.TenantRole tenant_roles = 51000;
	E_TenantRoles = &file_fits_api_v1_common_proto_extTypes[0]
	// ProjectRoles are used to define which project role a logged in user must provide to call this method
	//
	// repeated fits.api.v1.ProjectRole project_roles = 51001;
	E_ProjectRoles = &file_fits_api_v1_common_proto_extTypes[1]
	// AdminRoles are used to define which admin role a logged in user must provide to call this method
	//
	// repeated fits.api.v1.AdminRole admin_roles = 51002;
	E_AdminRoles = &file_fits_api_v1_common_proto_extTypes[2]
	// Visibility defines the visibility of this method, this is used to have public or self visible methods
	//
	// optional fits.api.v1.Visibility visibility = 51003;
	E_Visibility = &file_fits_api_v1_common_proto_extTypes[3]
	// Auditing defines if calls to this method should be audited or not
	//
	// optional fits.api.v1.Auditing auditing = 51004;
	E_Auditing = &file_fits_api_v1_common_proto_extTypes[4]
)

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// StringValue which can be set to a enum
	//
	// optional string enum_string_value = 52000;
	E_EnumStringValue = &file_fits_api_v1_common_proto_extTypes[5]
)

var File_fits_api_v1_common_proto protoreflect.FileDescriptor

const file_fits_api_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x18fits/api/v1/common.proto\x12\vfits.api.v1\x1a\x1bbuf/validate/validate.proto\x1a\"fits/api/v1/predefined_rules.proto\x1a google/protobuf/descriptor.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"O\n" +
	"\x06Paging\x12\x17\n" +
	"\x04page\x18\x01 \x01(\x04H\x00R\x04page\x88\x01\x01\x12\x19\n" +
	"\x05count\x18\x02 \x01(\x04H\x01R\x05count\x88\x01\x01B\a\n" +
	"\x05_pageB\b\n" +
	"\x06_count\"\x9c\x01\n" +
	"\x06Labels\x12W\n" +
	"\x06labels\x18\x01 \x03(\v2\x1f.fits.api.v1.Labels.LabelsEntryB\x1e\xbaH\x1b\x9a\x01\x18\xb8\x95\xb8\xb1\x02\x01\"\ar\x05\x10\x01\x18\x80\x02*\ar\x05\x10\x00\x18\x80\x02R\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd9\x01\n" +
	"\x04Meta\x120\n" +
	"\x06labels\x18\x01 \x01(\v2\x13.fits.api.v1.LabelsH\x00R\x06labels\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1e\n" +
	"\n" +
	"generation\x18\x04 \x01(\x04R\n" +
	"generationB\t\n" +
	"\a_labels\"S\n" +
	"\fUpdateLabels\x12+\n" +
	"\x06update\x18\x01 \x01(\v2\x13.fits.api.v1.LabelsR\x06update\x12\x16\n" +
	"\x06remove\x18\x02 \x03(\tR\x06remove\"\xa4\x01\n" +
	"\n" +
	"UpdateMeta\x129\n" +
	"\n" +
	"updated_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12[\n" +
	"\x10locking_strategy\x18\x02 \x01(\x0e2&.fits.api.v1.OptimisticLockingStrategyB\b\xbaH\x05\x82\x01\x02\x10\x01R\x0flockingStrategy*\x87\x01\n" +
	"\n" +
	"TenantRole\x12\x1b\n" +
	"\x17TENANT_ROLE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11TENANT_ROLE_OWNER\x10\x01\x12\x16\n" +
	"\x12TENANT_ROLE_EDITOR\x10\x02\x12\x16\n" +
	"\x12TENANT_ROLE_VIEWER\x10\x03\x12\x15\n" +
	"\x11TENANT_ROLE_GUEST\x10\x04*u\n" +
	"\vProjectRole\x12\x1c\n" +
	"\x18PROJECT_ROLE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12PROJECT_ROLE_OWNER\x10\x01\x12\x17\n" +
	"\x13PROJECT_ROLE_EDITOR\x10\x02\x12\x17\n" +
	"\x13PROJECT_ROLE_VIEWER\x10\x03*U\n" +
	"\tAdminRole\x12\x1a\n" +
	"\x16ADMIN_ROLE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ADMIN_ROLE_EDITOR\x10\x01\x12\x15\n" +
	"\x11ADMIN_ROLE_VIEWER\x10\x02*U\n" +
	"\tInfraRole\x12\x1a\n" +
	"\x16INFRA_ROLE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11INFRA_ROLE_EDITOR\x10\x01\x12\x15\n" +
	"\x11INFRA_ROLE_VIEWER\x10\x02*]\n" +
	"\vMachineRole\x12\x1c\n" +
	"\x18MACHINE_ROLE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13MACHINE_ROLE_EDITOR\x10\x01\x12\x17\n" +
	"\x13MACHINE_ROLE_VIEWER\x10\x02*T\n" +
	"\n" +
	"Visibility\x12\x1a\n" +
	"\x16VISIBILITY_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11VISIBILITY_PUBLIC\x10\x01\x12\x13\n" +
	"\x0fVISIBILITY_SELF\x10\x02*R\n" +
	"\bAuditing\x12\x18\n" +
	"\x14AUDITING_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11AUDITING_INCLUDED\x10\x01\x12\x15\n" +
	"\x11AUDITING_EXCLUDED\x10\x02*\x98\x01\n" +
	"\x19OptimisticLockingStrategy\x12+\n" +
	"'OPTIMISTIC_LOCKING_STRATEGY_UNSPECIFIED\x10\x00\x12&\n" +
	"\"OPTIMISTIC_LOCKING_STRATEGY_CLIENT\x10\x01\x12&\n" +
	"\"OPTIMISTIC_LOCKING_STRATEGY_SERVER\x10\x02:\\\n" +
	"\ftenant_roles\x12\x1e.google.protobuf.MethodOptions\x18\xb8\x8e\x03 \x03(\x0e2\x17.fits.api.v1.TenantRoleR\vtenantRoles:_\n" +
	"\rproject_roles\x12\x1e.google.protobuf.MethodOptions\x18\xb9\x8e\x03 \x03(\x0e2\x18.fits.api.v1.ProjectRoleR\fprojectRoles:Y\n" +
	"\vadmin_roles\x12\x1e.google.protobuf.MethodOptions\x18\xba\x8e\x03 \x03(\x0e2\x16.fits.api.v1.AdminRoleR\n" +
	"adminRoles:Y\n" +
	"\n" +
	"visibility\x12\x1e.google.protobuf.MethodOptions\x18\xbb\x8e\x03 \x01(\x0e2\x17.fits.api.v1.VisibilityR\n" +
	"visibility:S\n" +
	"\bauditing\x12\x1e.google.protobuf.MethodOptions\x18\xbc\x8e\x03 \x01(\x0e2\x15.fits.api.v1.AuditingR\bauditing:O\n" +
	"\x11enum_string_value\x12!.google.protobuf.EnumValueOptions\x18\xa0\x96\x03 \x01(\tR\x0fenumStringValueB\x97\x01\n" +
	"\x0fcom.fits.api.v1B\vCommonProtoP\x01Z)github.com/fi-ts/api/go/fits/api/v1;apiv1\xa2\x02\x03FAX\xaa\x02\vFits.Api.V1\xca\x02\vFits\\Api\\V1\xe2\x02\x17Fits\\Api\\V1\\GPBMetadata\xea\x02\rFits::Api::V1b\x06proto3"

var (
	file_fits_api_v1_common_proto_rawDescOnce sync.Once
	file_fits_api_v1_common_proto_rawDescData []byte
)

func file_fits_api_v1_common_proto_rawDescGZIP() []byte {
	file_fits_api_v1_common_proto_rawDescOnce.Do(func() {
		file_fits_api_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fits_api_v1_common_proto_rawDesc), len(file_fits_api_v1_common_proto_rawDesc)))
	})
	return file_fits_api_v1_common_proto_rawDescData
}

var file_fits_api_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 8)
var file_fits_api_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_fits_api_v1_common_proto_goTypes = []any{
	(TenantRole)(0),                       // 0: fits.api.v1.TenantRole
	(ProjectRole)(0),                      // 1: fits.api.v1.ProjectRole
	(AdminRole)(0),                        // 2: fits.api.v1.AdminRole
	(InfraRole)(0),                        // 3: fits.api.v1.InfraRole
	(MachineRole)(0),                      // 4: fits.api.v1.MachineRole
	(Visibility)(0),                       // 5: fits.api.v1.Visibility
	(Auditing)(0),                         // 6: fits.api.v1.Auditing
	(OptimisticLockingStrategy)(0),        // 7: fits.api.v1.OptimisticLockingStrategy
	(*Paging)(nil),                        // 8: fits.api.v1.Paging
	(*Labels)(nil),                        // 9: fits.api.v1.Labels
	(*Meta)(nil),                          // 10: fits.api.v1.Meta
	(*UpdateLabels)(nil),                  // 11: fits.api.v1.UpdateLabels
	(*UpdateMeta)(nil),                    // 12: fits.api.v1.UpdateMeta
	nil,                                   // 13: fits.api.v1.Labels.LabelsEntry
	(*timestamppb.Timestamp)(nil),         // 14: google.protobuf.Timestamp
	(*descriptorpb.MethodOptions)(nil),    // 15: google.protobuf.MethodOptions
	(*descriptorpb.EnumValueOptions)(nil), // 16: google.protobuf.EnumValueOptions
}
var file_fits_api_v1_common_proto_depIdxs = []int32{
	13, // 0: fits.api.v1.Labels.labels:type_name -> fits.api.v1.Labels.LabelsEntry
	9,  // 1: fits.api.v1.Meta.labels:type_name -> fits.api.v1.Labels
	14, // 2: fits.api.v1.Meta.created_at:type_name -> google.protobuf.Timestamp
	14, // 3: fits.api.v1.Meta.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 4: fits.api.v1.UpdateLabels.update:type_name -> fits.api.v1.Labels
	14, // 5: fits.api.v1.UpdateMeta.updated_at:type_name -> google.protobuf.Timestamp
	7,  // 6: fits.api.v1.UpdateMeta.locking_strategy:type_name -> fits.api.v1.OptimisticLockingStrategy
	15, // 7: fits.api.v1.tenant_roles:extendee -> google.protobuf.MethodOptions
	15, // 8: fits.api.v1.project_roles:extendee -> google.protobuf.MethodOptions
	15, // 9: fits.api.v1.admin_roles:extendee -> google.protobuf.MethodOptions
	15, // 10: fits.api.v1.visibility:extendee -> google.protobuf.MethodOptions
	15, // 11: fits.api.v1.auditing:extendee -> google.protobuf.MethodOptions
	16, // 12: fits.api.v1.enum_string_value:extendee -> google.protobuf.EnumValueOptions
	0,  // 13: fits.api.v1.tenant_roles:type_name -> fits.api.v1.TenantRole
	1,  // 14: fits.api.v1.project_roles:type_name -> fits.api.v1.ProjectRole
	2,  // 15: fits.api.v1.admin_roles:type_name -> fits.api.v1.AdminRole
	5,  // 16: fits.api.v1.visibility:type_name -> fits.api.v1.Visibility
	6,  // 17: fits.api.v1.auditing:type_name -> fits.api.v1.Auditing
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	13, // [13:18] is the sub-list for extension type_name
	7,  // [7:13] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_fits_api_v1_common_proto_init() }
func file_fits_api_v1_common_proto_init() {
	if File_fits_api_v1_common_proto != nil {
		return
	}
	file_fits_api_v1_predefined_rules_proto_init()
	file_fits_api_v1_common_proto_msgTypes[0].OneofWrappers = []any{}
	file_fits_api_v1_common_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fits_api_v1_common_proto_rawDesc), len(file_fits_api_v1_common_proto_rawDesc)),
			NumEnums:      8,
			NumMessages:   6,
			NumExtensions: 6,
			NumServices:   0,
		},
		GoTypes:           file_fits_api_v1_common_proto_goTypes,
		DependencyIndexes: file_fits_api_v1_common_proto_depIdxs,
		EnumInfos:         file_fits_api_v1_common_proto_enumTypes,
		MessageInfos:      file_fits_api_v1_common_proto_msgTypes,
		ExtensionInfos:    file_fits_api_v1_common_proto_extTypes,
	}.Build()
	File_fits_api_v1_common_proto = out.File
	file_fits_api_v1_common_proto_goTypes = nil
	file_fits_api_v1_common_proto_depIdxs = nil
}
