// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: fits/api/v1/project.proto

package apiv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Project defines a group of resources belonging to a tenant
// a tenant can have multiple projects
type Project struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Uuid of this project
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// Meta for this project
	Meta *Meta `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	// Name of this project must be unique per tenant
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Description of this project
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Tenant this project belongs to
	Tenant string `protobuf:"bytes,5,opt,name=tenant,proto3" json:"tenant,omitempty"`
	// AvatarUrl of the Project
	AvatarUrl     *string `protobuf:"bytes,6,opt,name=avatar_url,json=avatarUrl,proto3,oneof" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_fits_api_v1_project_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_fits_api_v1_project_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_fits_api_v1_project_proto_rawDescGZIP(), []int{0}
}

func (x *Project) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Project) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Project) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *Project) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

// ProjectServiceListRequest is the request payload to list all projects
type ProjectServiceListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id lists only projects with this id
	Id *string `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	// Name lists only projects with this name
	Name *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// Tenant lists only projects of this tenant
	Tenant *string `protobuf:"bytes,3,opt,name=tenant,proto3,oneof" json:"tenant,omitempty"`
	// Labels lists only projects containing the given labels
	Labels        *Labels `protobuf:"bytes,4,opt,name=labels,proto3,oneof" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceListRequest) Reset() {
	*x = ProjectServiceListRequest{}
	mi := &file_fits_api_v1_project_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceListRequest) ProtoMessage() {}

func (x *ProjectServiceListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fits_api_v1_project_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceListRequest.ProtoReflect.Descriptor instead.
func (*ProjectServiceListRequest) Descriptor() ([]byte, []int) {
	return file_fits_api_v1_project_proto_rawDescGZIP(), []int{1}
}

func (x *ProjectServiceListRequest) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *ProjectServiceListRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *ProjectServiceListRequest) GetTenant() string {
	if x != nil && x.Tenant != nil {
		return *x.Tenant
	}
	return ""
}

func (x *ProjectServiceListRequest) GetLabels() *Labels {
	if x != nil {
		return x.Labels
	}
	return nil
}

// ProjectServiceListResponse is the response payload to list all projects
type ProjectServiceListResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Projects is a list of all your projects
	Projects      []*Project `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceListResponse) Reset() {
	*x = ProjectServiceListResponse{}
	mi := &file_fits_api_v1_project_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceListResponse) ProtoMessage() {}

func (x *ProjectServiceListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fits_api_v1_project_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceListResponse.ProtoReflect.Descriptor instead.
func (*ProjectServiceListResponse) Descriptor() ([]byte, []int) {
	return file_fits_api_v1_project_proto_rawDescGZIP(), []int{2}
}

func (x *ProjectServiceListResponse) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

// ProjectServiceGetRequest is the request payload to get a project
type ProjectServiceGetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Project is the uuid of the project to get
	Project       string `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceGetRequest) Reset() {
	*x = ProjectServiceGetRequest{}
	mi := &file_fits_api_v1_project_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceGetRequest) ProtoMessage() {}

func (x *ProjectServiceGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fits_api_v1_project_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceGetRequest.ProtoReflect.Descriptor instead.
func (*ProjectServiceGetRequest) Descriptor() ([]byte, []int) {
	return file_fits_api_v1_project_proto_rawDescGZIP(), []int{3}
}

func (x *ProjectServiceGetRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

// ProjectServiceGetResponse is the response payload to get a projects
type ProjectServiceGetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Project is the project
	Project       *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceGetResponse) Reset() {
	*x = ProjectServiceGetResponse{}
	mi := &file_fits_api_v1_project_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceGetResponse) ProtoMessage() {}

func (x *ProjectServiceGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fits_api_v1_project_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceGetResponse.ProtoReflect.Descriptor instead.
func (*ProjectServiceGetResponse) Descriptor() ([]byte, []int) {
	return file_fits_api_v1_project_proto_rawDescGZIP(), []int{4}
}

func (x *ProjectServiceGetResponse) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

// ProjectServiceCreateRequest is the request payload to Create a project
type ProjectServiceCreateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Login is the tenant of this project
	// TODO: is login really a good name?
	Login string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	// Name of this project, unique per tenant
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Description of this project
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Avatar URL of the project
	AvatarUrl *string `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3,oneof" json:"avatar_url,omitempty"`
	// Labels on the project
	Labels        *Labels `protobuf:"bytes,5,opt,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceCreateRequest) Reset() {
	*x = ProjectServiceCreateRequest{}
	mi := &file_fits_api_v1_project_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceCreateRequest) ProtoMessage() {}

func (x *ProjectServiceCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fits_api_v1_project_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceCreateRequest.ProtoReflect.Descriptor instead.
func (*ProjectServiceCreateRequest) Descriptor() ([]byte, []int) {
	return file_fits_api_v1_project_proto_rawDescGZIP(), []int{5}
}

func (x *ProjectServiceCreateRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *ProjectServiceCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectServiceCreateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProjectServiceCreateRequest) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

func (x *ProjectServiceCreateRequest) GetLabels() *Labels {
	if x != nil {
		return x.Labels
	}
	return nil
}

// ProjectServiceCreateResponse is the response payload of creation of a project
type ProjectServiceCreateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Project is the project
	Project       *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceCreateResponse) Reset() {
	*x = ProjectServiceCreateResponse{}
	mi := &file_fits_api_v1_project_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceCreateResponse) ProtoMessage() {}

func (x *ProjectServiceCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fits_api_v1_project_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceCreateResponse.ProtoReflect.Descriptor instead.
func (*ProjectServiceCreateResponse) Descriptor() ([]byte, []int) {
	return file_fits_api_v1_project_proto_rawDescGZIP(), []int{6}
}

func (x *ProjectServiceCreateResponse) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

// ProjectServiceDeleteRequest is the request payload to delete a project
type ProjectServiceDeleteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Project is the uuid of the project to get
	Project       string `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceDeleteRequest) Reset() {
	*x = ProjectServiceDeleteRequest{}
	mi := &file_fits_api_v1_project_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceDeleteRequest) ProtoMessage() {}

func (x *ProjectServiceDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fits_api_v1_project_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceDeleteRequest.ProtoReflect.Descriptor instead.
func (*ProjectServiceDeleteRequest) Descriptor() ([]byte, []int) {
	return file_fits_api_v1_project_proto_rawDescGZIP(), []int{7}
}

func (x *ProjectServiceDeleteRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

// ProjectServiceDeleteResponse is the response payload to delete a project
type ProjectServiceDeleteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Project is the project
	Project       *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceDeleteResponse) Reset() {
	*x = ProjectServiceDeleteResponse{}
	mi := &file_fits_api_v1_project_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceDeleteResponse) ProtoMessage() {}

func (x *ProjectServiceDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fits_api_v1_project_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceDeleteResponse.ProtoReflect.Descriptor instead.
func (*ProjectServiceDeleteResponse) Descriptor() ([]byte, []int) {
	return file_fits_api_v1_project_proto_rawDescGZIP(), []int{8}
}

func (x *ProjectServiceDeleteResponse) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

// ProjectServiceUpdateRequest is the request payload to update a project
type ProjectServiceUpdateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Project is the uuid of the project to get
	Project string `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	// UpdateMeta contains the timestamp and strategy to be used in this update request
	UpdateMeta *UpdateMeta `protobuf:"bytes,2,opt,name=update_meta,json=updateMeta,proto3" json:"update_meta,omitempty"`
	// Name of this project unique per tenant
	Name *string `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// Description of this project
	Description *string `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// Avatar URL of the project
	AvatarUrl *string `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3,oneof" json:"avatar_url,omitempty"`
	// Labels on this project
	Labels        *UpdateLabels `protobuf:"bytes,6,opt,name=labels,proto3,oneof" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceUpdateRequest) Reset() {
	*x = ProjectServiceUpdateRequest{}
	mi := &file_fits_api_v1_project_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceUpdateRequest) ProtoMessage() {}

func (x *ProjectServiceUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fits_api_v1_project_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceUpdateRequest.ProtoReflect.Descriptor instead.
func (*ProjectServiceUpdateRequest) Descriptor() ([]byte, []int) {
	return file_fits_api_v1_project_proto_rawDescGZIP(), []int{9}
}

func (x *ProjectServiceUpdateRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *ProjectServiceUpdateRequest) GetUpdateMeta() *UpdateMeta {
	if x != nil {
		return x.UpdateMeta
	}
	return nil
}

func (x *ProjectServiceUpdateRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *ProjectServiceUpdateRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *ProjectServiceUpdateRequest) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

func (x *ProjectServiceUpdateRequest) GetLabels() *UpdateLabels {
	if x != nil {
		return x.Labels
	}
	return nil
}

// ProjectServiceUpdateResponse is the response payload to update a project
type ProjectServiceUpdateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Project is the project
	Project       *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceUpdateResponse) Reset() {
	*x = ProjectServiceUpdateResponse{}
	mi := &file_fits_api_v1_project_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceUpdateResponse) ProtoMessage() {}

func (x *ProjectServiceUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fits_api_v1_project_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceUpdateResponse.ProtoReflect.Descriptor instead.
func (*ProjectServiceUpdateResponse) Descriptor() ([]byte, []int) {
	return file_fits_api_v1_project_proto_rawDescGZIP(), []int{10}
}

func (x *ProjectServiceUpdateResponse) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

var File_fits_api_v1_project_proto protoreflect.FileDescriptor

const file_fits_api_v1_project_proto_rawDesc = "" +
	"\n" +
	"\x19fits/api/v1/project.proto\x12\vfits.api.v1\x1a\x1bbuf/validate/validate.proto\x1a\x18fits/api/v1/common.proto\x1a\"fits/api/v1/predefined_rules.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdf\x01\n" +
	"\aProject\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12%\n" +
	"\x04meta\x18\x02 \x01(\v2\x11.fits.api.v1.MetaR\x04meta\x12\x1f\n" +
	"\x04name\x18\x03 \x01(\tB\v\xbaH\br\x06\xc0\xb3\xae\xb1\x02\x01R\x04name\x12-\n" +
	"\vdescription\x18\x04 \x01(\tB\v\xbaH\br\x06ȳ\xae\xb1\x02\x01R\vdescription\x12\x16\n" +
	"\x06tenant\x18\x05 \x01(\tR\x06tenant\x12\"\n" +
	"\n" +
	"avatar_url\x18\x06 \x01(\tH\x00R\tavatarUrl\x88\x01\x01B\r\n" +
	"\v_avatar_url\"\xd8\x01\n" +
	"\x19ProjectServiceListRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12$\n" +
	"\x04name\x18\x02 \x01(\tB\v\xbaH\br\x06\xc0\xb3\xae\xb1\x02\x01H\x01R\x04name\x88\x01\x01\x12(\n" +
	"\x06tenant\x18\x03 \x01(\tB\v\xbaH\br\x06\xc0\xb3\xae\xb1\x02\x01H\x02R\x06tenant\x88\x01\x01\x120\n" +
	"\x06labels\x18\x04 \x01(\v2\x13.fits.api.v1.LabelsH\x03R\x06labels\x88\x01\x01B\x05\n" +
	"\x03_idB\a\n" +
	"\x05_nameB\t\n" +
	"\a_tenantB\t\n" +
	"\a_labels\"N\n" +
	"\x1aProjectServiceListResponse\x120\n" +
	"\bprojects\x18\x01 \x03(\v2\x14.fits.api.v1.ProjectR\bprojects\">\n" +
	"\x18ProjectServiceGetRequest\x12\"\n" +
	"\aproject\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\aproject\"K\n" +
	"\x19ProjectServiceGetResponse\x12.\n" +
	"\aproject\x18\x01 \x01(\v2\x14.fits.api.v1.ProjectR\aproject\"\xf0\x01\n" +
	"\x1bProjectServiceCreateRequest\x12!\n" +
	"\x05login\x18\x01 \x01(\tB\v\xbaH\br\x06\xc0\xb3\xae\xb1\x02\x01R\x05login\x12\x1f\n" +
	"\x04name\x18\x02 \x01(\tB\v\xbaH\br\x06\xc0\xb3\xae\xb1\x02\x01R\x04name\x12-\n" +
	"\vdescription\x18\x03 \x01(\tB\v\xbaH\br\x06ȳ\xae\xb1\x02\x01R\vdescription\x12\"\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tH\x00R\tavatarUrl\x88\x01\x01\x12+\n" +
	"\x06labels\x18\x05 \x01(\v2\x13.fits.api.v1.LabelsR\x06labelsB\r\n" +
	"\v_avatar_url\"N\n" +
	"\x1cProjectServiceCreateResponse\x12.\n" +
	"\aproject\x18\x01 \x01(\v2\x14.fits.api.v1.ProjectR\aproject\"A\n" +
	"\x1bProjectServiceDeleteRequest\x12\"\n" +
	"\aproject\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\aproject\"N\n" +
	"\x1cProjectServiceDeleteResponse\x12.\n" +
	"\aproject\x18\x01 \x01(\v2\x14.fits.api.v1.ProjectR\aproject\"\xec\x02\n" +
	"\x1bProjectServiceUpdateRequest\x12\"\n" +
	"\aproject\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\aproject\x12@\n" +
	"\vupdate_meta\x18\x02 \x01(\v2\x17.fits.api.v1.UpdateMetaB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"updateMeta\x12$\n" +
	"\x04name\x18\x03 \x01(\tB\v\xbaH\br\x06\xc0\xb3\xae\xb1\x02\x01H\x00R\x04name\x88\x01\x01\x122\n" +
	"\vdescription\x18\x04 \x01(\tB\v\xbaH\br\x06ȳ\xae\xb1\x02\x01H\x01R\vdescription\x88\x01\x01\x12\"\n" +
	"\n" +
	"avatar_url\x18\x05 \x01(\tH\x02R\tavatarUrl\x88\x01\x01\x126\n" +
	"\x06labels\x18\x06 \x01(\v2\x19.fits.api.v1.UpdateLabelsH\x03R\x06labels\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\r\n" +
	"\v_avatar_urlB\t\n" +
	"\a_labels\"N\n" +
	"\x1cProjectServiceUpdateResponse\x12.\n" +
	"\aproject\x18\x01 \x01(\v2\x14.fits.api.v1.ProjectR\aproject2\x96\x04\n" +
	"\x0eProjectService\x12a\n" +
	"\x04List\x12&.fits.api.v1.ProjectServiceListRequest\x1a'.fits.api.v1.ProjectServiceListResponse\"\b\xd8\xf3\x18\x02\xe0\xf3\x18\x02\x12a\n" +
	"\x03Get\x12%.fits.api.v1.ProjectServiceGetRequest\x1a&.fits.api.v1.ProjectServiceGetResponse\"\v\xca\xf3\x18\x03\x01\x02\x03\xe0\xf3\x18\x02\x12i\n" +
	"\x06Create\x12(.fits.api.v1.ProjectServiceCreateRequest\x1a).fits.api.v1.ProjectServiceCreateResponse\"\n" +
	"\xc2\xf3\x18\x02\x01\x02\xe0\xf3\x18\x01\x12h\n" +
	"\x06Delete\x12(.fits.api.v1.ProjectServiceDeleteRequest\x1a).fits.api.v1.ProjectServiceDeleteResponse\"\t\xca\xf3\x18\x01\x01\xe0\xf3\x18\x01\x12i\n" +
	"\x06Update\x12(.fits.api.v1.ProjectServiceUpdateRequest\x1a).fits.api.v1.ProjectServiceUpdateResponse\"\n" +
	"\xca\xf3\x18\x02\x01\x02\xe0\xf3\x18\x01B\x98\x01\n" +
	"\x0fcom.fits.api.v1B\fProjectProtoP\x01Z)github.com/fi-ts/api/go/fits/api/v1;apiv1\xa2\x02\x03FAX\xaa\x02\vFits.Api.V1\xca\x02\vFits\\Api\\V1\xe2\x02\x17Fits\\Api\\V1\\GPBMetadata\xea\x02\rFits::Api::V1b\x06proto3"

var (
	file_fits_api_v1_project_proto_rawDescOnce sync.Once
	file_fits_api_v1_project_proto_rawDescData []byte
)

func file_fits_api_v1_project_proto_rawDescGZIP() []byte {
	file_fits_api_v1_project_proto_rawDescOnce.Do(func() {
		file_fits_api_v1_project_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fits_api_v1_project_proto_rawDesc), len(file_fits_api_v1_project_proto_rawDesc)))
	})
	return file_fits_api_v1_project_proto_rawDescData
}

var file_fits_api_v1_project_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_fits_api_v1_project_proto_goTypes = []any{
	(*Project)(nil),                      // 0: fits.api.v1.Project
	(*ProjectServiceListRequest)(nil),    // 1: fits.api.v1.ProjectServiceListRequest
	(*ProjectServiceListResponse)(nil),   // 2: fits.api.v1.ProjectServiceListResponse
	(*ProjectServiceGetRequest)(nil),     // 3: fits.api.v1.ProjectServiceGetRequest
	(*ProjectServiceGetResponse)(nil),    // 4: fits.api.v1.ProjectServiceGetResponse
	(*ProjectServiceCreateRequest)(nil),  // 5: fits.api.v1.ProjectServiceCreateRequest
	(*ProjectServiceCreateResponse)(nil), // 6: fits.api.v1.ProjectServiceCreateResponse
	(*ProjectServiceDeleteRequest)(nil),  // 7: fits.api.v1.ProjectServiceDeleteRequest
	(*ProjectServiceDeleteResponse)(nil), // 8: fits.api.v1.ProjectServiceDeleteResponse
	(*ProjectServiceUpdateRequest)(nil),  // 9: fits.api.v1.ProjectServiceUpdateRequest
	(*ProjectServiceUpdateResponse)(nil), // 10: fits.api.v1.ProjectServiceUpdateResponse
	(*Meta)(nil),                         // 11: fits.api.v1.Meta
	(*Labels)(nil),                       // 12: fits.api.v1.Labels
	(*UpdateMeta)(nil),                   // 13: fits.api.v1.UpdateMeta
	(*UpdateLabels)(nil),                 // 14: fits.api.v1.UpdateLabels
}
var file_fits_api_v1_project_proto_depIdxs = []int32{
	11, // 0: fits.api.v1.Project.meta:type_name -> fits.api.v1.Meta
	12, // 1: fits.api.v1.ProjectServiceListRequest.labels:type_name -> fits.api.v1.Labels
	0,  // 2: fits.api.v1.ProjectServiceListResponse.projects:type_name -> fits.api.v1.Project
	0,  // 3: fits.api.v1.ProjectServiceGetResponse.project:type_name -> fits.api.v1.Project
	12, // 4: fits.api.v1.ProjectServiceCreateRequest.labels:type_name -> fits.api.v1.Labels
	0,  // 5: fits.api.v1.ProjectServiceCreateResponse.project:type_name -> fits.api.v1.Project
	0,  // 6: fits.api.v1.ProjectServiceDeleteResponse.project:type_name -> fits.api.v1.Project
	13, // 7: fits.api.v1.ProjectServiceUpdateRequest.update_meta:type_name -> fits.api.v1.UpdateMeta
	14, // 8: fits.api.v1.ProjectServiceUpdateRequest.labels:type_name -> fits.api.v1.UpdateLabels
	0,  // 9: fits.api.v1.ProjectServiceUpdateResponse.project:type_name -> fits.api.v1.Project
	1,  // 10: fits.api.v1.ProjectService.List:input_type -> fits.api.v1.ProjectServiceListRequest
	3,  // 11: fits.api.v1.ProjectService.Get:input_type -> fits.api.v1.ProjectServiceGetRequest
	5,  // 12: fits.api.v1.ProjectService.Create:input_type -> fits.api.v1.ProjectServiceCreateRequest
	7,  // 13: fits.api.v1.ProjectService.Delete:input_type -> fits.api.v1.ProjectServiceDeleteRequest
	9,  // 14: fits.api.v1.ProjectService.Update:input_type -> fits.api.v1.ProjectServiceUpdateRequest
	2,  // 15: fits.api.v1.ProjectService.List:output_type -> fits.api.v1.ProjectServiceListResponse
	4,  // 16: fits.api.v1.ProjectService.Get:output_type -> fits.api.v1.ProjectServiceGetResponse
	6,  // 17: fits.api.v1.ProjectService.Create:output_type -> fits.api.v1.ProjectServiceCreateResponse
	8,  // 18: fits.api.v1.ProjectService.Delete:output_type -> fits.api.v1.ProjectServiceDeleteResponse
	10, // 19: fits.api.v1.ProjectService.Update:output_type -> fits.api.v1.ProjectServiceUpdateResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_fits_api_v1_project_proto_init() }
func file_fits_api_v1_project_proto_init() {
	if File_fits_api_v1_project_proto != nil {
		return
	}
	file_fits_api_v1_common_proto_init()
	file_fits_api_v1_predefined_rules_proto_init()
	file_fits_api_v1_project_proto_msgTypes[0].OneofWrappers = []any{}
	file_fits_api_v1_project_proto_msgTypes[1].OneofWrappers = []any{}
	file_fits_api_v1_project_proto_msgTypes[5].OneofWrappers = []any{}
	file_fits_api_v1_project_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fits_api_v1_project_proto_rawDesc), len(file_fits_api_v1_project_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fits_api_v1_project_proto_goTypes,
		DependencyIndexes: file_fits_api_v1_project_proto_depIdxs,
		MessageInfos:      file_fits_api_v1_project_proto_msgTypes,
	}.Build()
	File_fits_api_v1_project_proto = out.File
	file_fits_api_v1_project_proto_goTypes = nil
	file_fits_api_v1_project_proto_depIdxs = nil
}
