syntax = "proto3";

package fits.api.mvm.v1;

import "buf/validate/validate.proto";
import "fits/api/v1/common.proto";
import "fits/api/v1/predefined_rules.proto";

// VLANService lists VLANs available for managed VM (MVM) instances.
service VLANService {
  // Returns a list of all VLANs available for a tenant.
  rpc List(VLANServiceListRequest) returns (VLANServiceListResponse) {
    option (fits.api.v1.tenant_roles) = TENANT_ROLE_OWNER;
    option (fits.api.v1.tenant_roles) = TENANT_ROLE_EDITOR;
    option (fits.api.v1.tenant_roles) = TENANT_ROLE_VIEWER;
    option (fits.api.v1.auditing) = AUDITING_EXCLUDED;
  }
}

// VLAN is a VLAN that a MVM can be connected to.
message VLAN {
  // UUID of this VLAN.
  string uuid = 1 [(buf.validate.field).string.uuid = true];
  // ID of this VLAN. The actual VLAN ID a network interface is attached to.
  int32 vlan_id = 2;
  // Title of the subnet this VLAN belongs to, including the stage type, e.g. "pod01-vlan2001 (Production)".
  string subnet_title = 3 [(buf.validate.field).string.(fits.api.v1.is_name) = true];
  // CIDR of the subnet this VLAN belongs to.
  string subnet_cidr = 4 [(buf.validate.field).string.(fits.api.v1.is_ipv4_cidr) = true];
  // UUID of the location this VLAN belongs to. This is actually the FCE datacenter ID.
  string location_uuid = 5 [(buf.validate.field).string.uuid = true];
  // Tenant this VLAN belongs to.
  string tenant = 6 [(buf.validate.field).string.(fits.api.v1.is_name) = true];
  // UUID of the Windows domain this VLAN is associated with. Only set for Windows.
  optional string domain_uuid = 7 [(buf.validate.field).string.uuid = true];
}

// VLANServiceListRequest is the request payload for a VLAN list request.
message VLANServiceListRequest {
  // Tenant to list available VLANs for (the tenant login).
  string tenant = 1 [(buf.validate.field).string.(fits.api.v1.is_name) = true];
  // Filter the listed VLANs by location (the FCE datacenter ID).
  string location_uuid = 2 [(buf.validate.field).string.uuid = true];
  // Filter the listed VLANs by the Windows domain they are associated with.
  optional string domain_uuid = 3 [(buf.validate.field).string.uuid = true];
}

// VLANServiceListResponse is the response payload for a VLAN list request.
message VLANServiceListResponse {
  // The available VLANs.
  repeated VLAN vlans = 1;
}
