// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package apiv1connect

import (
	"context"

	"github.com/fi-ts/api/go/fits/api/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewTokenServiceHandler creates a new instance of TokenServiceHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenServiceHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenServiceHandler {
	mock := &TokenServiceHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TokenServiceHandler is an autogenerated mock type for the TokenServiceHandler type
type TokenServiceHandler struct {
	mock.Mock
}

type TokenServiceHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenServiceHandler) EXPECT() *TokenServiceHandler_Expecter {
	return &TokenServiceHandler_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type TokenServiceHandler
func (_mock *TokenServiceHandler) Create(context1 context.Context, tokenServiceCreateRequest *apiv1.TokenServiceCreateRequest) (*apiv1.TokenServiceCreateResponse, error) {
	ret := _mock.Called(context1, tokenServiceCreateRequest)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *apiv1.TokenServiceCreateResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TokenServiceCreateRequest) (*apiv1.TokenServiceCreateResponse, error)); ok {
		return returnFunc(context1, tokenServiceCreateRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TokenServiceCreateRequest) *apiv1.TokenServiceCreateResponse); ok {
		r0 = returnFunc(context1, tokenServiceCreateRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.TokenServiceCreateResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.TokenServiceCreateRequest) error); ok {
		r1 = returnFunc(context1, tokenServiceCreateRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenServiceHandler_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type TokenServiceHandler_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - tokenServiceCreateRequest *apiv1.TokenServiceCreateRequest
func (_e *TokenServiceHandler_Expecter) Create(context1 interface{}, tokenServiceCreateRequest interface{}) *TokenServiceHandler_Create_Call {
	return &TokenServiceHandler_Create_Call{Call: _e.mock.On("Create", context1, tokenServiceCreateRequest)}
}

func (_c *TokenServiceHandler_Create_Call) Run(run func(context1 context.Context, tokenServiceCreateRequest *apiv1.TokenServiceCreateRequest)) *TokenServiceHandler_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.TokenServiceCreateRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.TokenServiceCreateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TokenServiceHandler_Create_Call) Return(tokenServiceCreateResponse *apiv1.TokenServiceCreateResponse, err error) *TokenServiceHandler_Create_Call {
	_c.Call.Return(tokenServiceCreateResponse, err)
	return _c
}

func (_c *TokenServiceHandler_Create_Call) RunAndReturn(run func(context1 context.Context, tokenServiceCreateRequest *apiv1.TokenServiceCreateRequest) (*apiv1.TokenServiceCreateResponse, error)) *TokenServiceHandler_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type TokenServiceHandler
func (_mock *TokenServiceHandler) Get(context1 context.Context, tokenServiceGetRequest *apiv1.TokenServiceGetRequest) (*apiv1.TokenServiceGetResponse, error) {
	ret := _mock.Called(context1, tokenServiceGetRequest)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *apiv1.TokenServiceGetResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TokenServiceGetRequest) (*apiv1.TokenServiceGetResponse, error)); ok {
		return returnFunc(context1, tokenServiceGetRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TokenServiceGetRequest) *apiv1.TokenServiceGetResponse); ok {
		r0 = returnFunc(context1, tokenServiceGetRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.TokenServiceGetResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.TokenServiceGetRequest) error); ok {
		r1 = returnFunc(context1, tokenServiceGetRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenServiceHandler_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type TokenServiceHandler_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - context1 context.Context
//   - tokenServiceGetRequest *apiv1.TokenServiceGetRequest
func (_e *TokenServiceHandler_Expecter) Get(context1 interface{}, tokenServiceGetRequest interface{}) *TokenServiceHandler_Get_Call {
	return &TokenServiceHandler_Get_Call{Call: _e.mock.On("Get", context1, tokenServiceGetRequest)}
}

func (_c *TokenServiceHandler_Get_Call) Run(run func(context1 context.Context, tokenServiceGetRequest *apiv1.TokenServiceGetRequest)) *TokenServiceHandler_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.TokenServiceGetRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.TokenServiceGetRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TokenServiceHandler_Get_Call) Return(tokenServiceGetResponse *apiv1.TokenServiceGetResponse, err error) *TokenServiceHandler_Get_Call {
	_c.Call.Return(tokenServiceGetResponse, err)
	return _c
}

func (_c *TokenServiceHandler_Get_Call) RunAndReturn(run func(context1 context.Context, tokenServiceGetRequest *apiv1.TokenServiceGetRequest) (*apiv1.TokenServiceGetResponse, error)) *TokenServiceHandler_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type TokenServiceHandler
func (_mock *TokenServiceHandler) List(context1 context.Context, tokenServiceListRequest *apiv1.TokenServiceListRequest) (*apiv1.TokenServiceListResponse, error) {
	ret := _mock.Called(context1, tokenServiceListRequest)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *apiv1.TokenServiceListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TokenServiceListRequest) (*apiv1.TokenServiceListResponse, error)); ok {
		return returnFunc(context1, tokenServiceListRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TokenServiceListRequest) *apiv1.TokenServiceListResponse); ok {
		r0 = returnFunc(context1, tokenServiceListRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.TokenServiceListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.TokenServiceListRequest) error); ok {
		r1 = returnFunc(context1, tokenServiceListRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenServiceHandler_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type TokenServiceHandler_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - context1 context.Context
//   - tokenServiceListRequest *apiv1.TokenServiceListRequest
func (_e *TokenServiceHandler_Expecter) List(context1 interface{}, tokenServiceListRequest interface{}) *TokenServiceHandler_List_Call {
	return &TokenServiceHandler_List_Call{Call: _e.mock.On("List", context1, tokenServiceListRequest)}
}

func (_c *TokenServiceHandler_List_Call) Run(run func(context1 context.Context, tokenServiceListRequest *apiv1.TokenServiceListRequest)) *TokenServiceHandler_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.TokenServiceListRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.TokenServiceListRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TokenServiceHandler_List_Call) Return(tokenServiceListResponse *apiv1.TokenServiceListResponse, err error) *TokenServiceHandler_List_Call {
	_c.Call.Return(tokenServiceListResponse, err)
	return _c
}

func (_c *TokenServiceHandler_List_Call) RunAndReturn(run func(context1 context.Context, tokenServiceListRequest *apiv1.TokenServiceListRequest) (*apiv1.TokenServiceListResponse, error)) *TokenServiceHandler_List_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function for the type TokenServiceHandler
func (_mock *TokenServiceHandler) Refresh(context1 context.Context, tokenServiceRefreshRequest *apiv1.TokenServiceRefreshRequest) (*apiv1.TokenServiceRefreshResponse, error) {
	ret := _mock.Called(context1, tokenServiceRefreshRequest)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 *apiv1.TokenServiceRefreshResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TokenServiceRefreshRequest) (*apiv1.TokenServiceRefreshResponse, error)); ok {
		return returnFunc(context1, tokenServiceRefreshRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TokenServiceRefreshRequest) *apiv1.TokenServiceRefreshResponse); ok {
		r0 = returnFunc(context1, tokenServiceRefreshRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.TokenServiceRefreshResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.TokenServiceRefreshRequest) error); ok {
		r1 = returnFunc(context1, tokenServiceRefreshRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenServiceHandler_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type TokenServiceHandler_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - context1 context.Context
//   - tokenServiceRefreshRequest *apiv1.TokenServiceRefreshRequest
func (_e *TokenServiceHandler_Expecter) Refresh(context1 interface{}, tokenServiceRefreshRequest interface{}) *TokenServiceHandler_Refresh_Call {
	return &TokenServiceHandler_Refresh_Call{Call: _e.mock.On("Refresh", context1, tokenServiceRefreshRequest)}
}

func (_c *TokenServiceHandler_Refresh_Call) Run(run func(context1 context.Context, tokenServiceRefreshRequest *apiv1.TokenServiceRefreshRequest)) *TokenServiceHandler_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.TokenServiceRefreshRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.TokenServiceRefreshRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TokenServiceHandler_Refresh_Call) Return(tokenServiceRefreshResponse *apiv1.TokenServiceRefreshResponse, err error) *TokenServiceHandler_Refresh_Call {
	_c.Call.Return(tokenServiceRefreshResponse, err)
	return _c
}

func (_c *TokenServiceHandler_Refresh_Call) RunAndReturn(run func(context1 context.Context, tokenServiceRefreshRequest *apiv1.TokenServiceRefreshRequest) (*apiv1.TokenServiceRefreshResponse, error)) *TokenServiceHandler_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function for the type TokenServiceHandler
func (_mock *TokenServiceHandler) Revoke(context1 context.Context, tokenServiceRevokeRequest *apiv1.TokenServiceRevokeRequest) (*apiv1.TokenServiceRevokeResponse, error) {
	ret := _mock.Called(context1, tokenServiceRevokeRequest)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 *apiv1.TokenServiceRevokeResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TokenServiceRevokeRequest) (*apiv1.TokenServiceRevokeResponse, error)); ok {
		return returnFunc(context1, tokenServiceRevokeRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TokenServiceRevokeRequest) *apiv1.TokenServiceRevokeResponse); ok {
		r0 = returnFunc(context1, tokenServiceRevokeRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.TokenServiceRevokeResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.TokenServiceRevokeRequest) error); ok {
		r1 = returnFunc(context1, tokenServiceRevokeRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenServiceHandler_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type TokenServiceHandler_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - context1 context.Context
//   - tokenServiceRevokeRequest *apiv1.TokenServiceRevokeRequest
func (_e *TokenServiceHandler_Expecter) Revoke(context1 interface{}, tokenServiceRevokeRequest interface{}) *TokenServiceHandler_Revoke_Call {
	return &TokenServiceHandler_Revoke_Call{Call: _e.mock.On("Revoke", context1, tokenServiceRevokeRequest)}
}

func (_c *TokenServiceHandler_Revoke_Call) Run(run func(context1 context.Context, tokenServiceRevokeRequest *apiv1.TokenServiceRevokeRequest)) *TokenServiceHandler_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.TokenServiceRevokeRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.TokenServiceRevokeRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TokenServiceHandler_Revoke_Call) Return(tokenServiceRevokeResponse *apiv1.TokenServiceRevokeResponse, err error) *TokenServiceHandler_Revoke_Call {
	_c.Call.Return(tokenServiceRevokeResponse, err)
	return _c
}

func (_c *TokenServiceHandler_Revoke_Call) RunAndReturn(run func(context1 context.Context, tokenServiceRevokeRequest *apiv1.TokenServiceRevokeRequest) (*apiv1.TokenServiceRevokeResponse, error)) *TokenServiceHandler_Revoke_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type TokenServiceHandler
func (_mock *TokenServiceHandler) Update(context1 context.Context, tokenServiceUpdateRequest *apiv1.TokenServiceUpdateRequest) (*apiv1.TokenServiceUpdateResponse, error) {
	ret := _mock.Called(context1, tokenServiceUpdateRequest)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *apiv1.TokenServiceUpdateResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TokenServiceUpdateRequest) (*apiv1.TokenServiceUpdateResponse, error)); ok {
		return returnFunc(context1, tokenServiceUpdateRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TokenServiceUpdateRequest) *apiv1.TokenServiceUpdateResponse); ok {
		r0 = returnFunc(context1, tokenServiceUpdateRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.TokenServiceUpdateResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.TokenServiceUpdateRequest) error); ok {
		r1 = returnFunc(context1, tokenServiceUpdateRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenServiceHandler_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type TokenServiceHandler_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - context1 context.Context
//   - tokenServiceUpdateRequest *apiv1.TokenServiceUpdateRequest
func (_e *TokenServiceHandler_Expecter) Update(context1 interface{}, tokenServiceUpdateRequest interface{}) *TokenServiceHandler_Update_Call {
	return &TokenServiceHandler_Update_Call{Call: _e.mock.On("Update", context1, tokenServiceUpdateRequest)}
}

func (_c *TokenServiceHandler_Update_Call) Run(run func(context1 context.Context, tokenServiceUpdateRequest *apiv1.TokenServiceUpdateRequest)) *TokenServiceHandler_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.TokenServiceUpdateRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.TokenServiceUpdateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TokenServiceHandler_Update_Call) Return(tokenServiceUpdateResponse *apiv1.TokenServiceUpdateResponse, err error) *TokenServiceHandler_Update_Call {
	_c.Call.Return(tokenServiceUpdateResponse, err)
	return _c
}

func (_c *TokenServiceHandler_Update_Call) RunAndReturn(run func(context1 context.Context, tokenServiceUpdateRequest *apiv1.TokenServiceUpdateRequest) (*apiv1.TokenServiceUpdateResponse, error)) *TokenServiceHandler_Update_Call {
	_c.Call.Return(run)
	return _c
}
