# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fits/api/v1/version.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'fits/api/v1/version.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2
from fits.api.v1 import common_pb2 as fits_dot_api_dot_v1_dot_common__pb2
from fits.api.v1 import predefined_rules_pb2 as fits_dot_api_dot_v1_dot_predefined__rules__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x66its/api/v1/version.proto\x12\x0b\x66its.api.v1\x1a\x1b\x62uf/validate/validate.proto\x1a\x18\x66its/api/v1/common.proto\x1a\"fits/api/v1/predefined_rules.proto\"\xad\x01\n\x07Version\x12%\n\x07version\x18\x01 \x01(\tB\x0b\xbaH\x08r\x06\xc8\xb3\xae\xb1\x02\x01R\x07version\x12\'\n\x08revision\x18\x02 \x01(\tB\x0b\xbaH\x08r\x06\xc8\xb3\xae\xb1\x02\x01R\x08revision\x12&\n\x08git_sha1\x18\x03 \x01(\tB\x0b\xbaH\x08r\x06\xc8\xb3\xae\xb1\x02\x01R\x07gitSha1\x12*\n\nbuild_date\x18\x04 \x01(\tB\x0b\xbaH\x08r\x06\xc8\xb3\xae\xb1\x02\x01R\tbuildDate\"\x1a\n\x18VersionServiceGetRequest\"K\n\x19VersionServiceGetResponse\x12.\n\x07version\x18\x01 \x01(\x0b\x32\x14.fits.api.v1.VersionR\x07version2p\n\x0eVersionService\x12^\n\x03Get\x12%.fits.api.v1.VersionServiceGetRequest\x1a&.fits.api.v1.VersionServiceGetResponse\"\x08\xd8\xf3\x18\x01\xe0\xf3\x18\x02\x42\x98\x01\n\x0f\x63om.fits.api.v1B\x0cVersionProtoP\x01Z)github.com/fi-ts/api/go/fits/api/v1;apiv1\xa2\x02\x03\x46\x41X\xaa\x02\x0b\x46its.Api.V1\xca\x02\x0b\x46its\\Api\\V1\xe2\x02\x17\x46its\\Api\\V1\\GPBMetadata\xea\x02\rFits::Api::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fits.api.v1.version_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\017com.fits.api.v1B\014VersionProtoP\001Z)github.com/fi-ts/api/go/fits/api/v1;apiv1\242\002\003FAX\252\002\013Fits.Api.V1\312\002\013Fits\\Api\\V1\342\002\027Fits\\Api\\V1\\GPBMetadata\352\002\rFits::Api::V1'
  _globals['_VERSION'].fields_by_name['version']._loaded_options = None
  _globals['_VERSION'].fields_by_name['version']._serialized_options = b'\272H\010r\006\310\263\256\261\002\001'
  _globals['_VERSION'].fields_by_name['revision']._loaded_options = None
  _globals['_VERSION'].fields_by_name['revision']._serialized_options = b'\272H\010r\006\310\263\256\261\002\001'
  _globals['_VERSION'].fields_by_name['git_sha1']._loaded_options = None
  _globals['_VERSION'].fields_by_name['git_sha1']._serialized_options = b'\272H\010r\006\310\263\256\261\002\001'
  _globals['_VERSION'].fields_by_name['build_date']._loaded_options = None
  _globals['_VERSION'].fields_by_name['build_date']._serialized_options = b'\272H\010r\006\310\263\256\261\002\001'
  _globals['_VERSIONSERVICE'].methods_by_name['Get']._loaded_options = None
  _globals['_VERSIONSERVICE'].methods_by_name['Get']._serialized_options = b'\330\363\030\001\340\363\030\002'
  _globals['_VERSION']._serialized_start=134
  _globals['_VERSION']._serialized_end=307
  _globals['_VERSIONSERVICEGETREQUEST']._serialized_start=309
  _globals['_VERSIONSERVICEGETREQUEST']._serialized_end=335
  _globals['_VERSIONSERVICEGETRESPONSE']._serialized_start=337
  _globals['_VERSIONSERVICEGETRESPONSE']._serialized_end=412
  _globals['_VERSIONSERVICE']._serialized_start=414
  _globals['_VERSIONSERVICE']._serialized_end=526
# @@protoc_insertion_point(module_scope)
