syntax = "proto3";

package fits.api.vm.v1;

import "buf/validate/validate.proto";
import "fits/api/v1/common.proto";
import "fits/api/v1/predefined_rules.proto";

// LocationService lists datacenter locations available for VM instances.
// TODO wurde besprochen am 09.09.26
// TODO muss zu "Pod" werden. User erstellen eine VM nicht pro location, sondern pro Pod
// TODO Ein Pod ist fest an einer location verankert.
service LocationService {
  // Returns a list of all datacenter locations.
  rpc List(LocationServiceListRequest) returns (LocationServiceListResponse) {
    option (fits.api.v1.project_roles) = PROJECT_ROLE_OWNER;
    option (fits.api.v1.project_roles) = PROJECT_ROLE_EDITOR;
    option (fits.api.v1.project_roles) = PROJECT_ROLE_VIEWER;
    option (fits.api.v1.auditing) = AUDITING_EXCLUDED;
  }
}

// Location is the definition of an available datacenter location for VM instances
message Location {
  // Uuid of this location
  string uuid = 1 [(buf.validate.field).string.uuid = true];
  // title of the location
  string title = 2;
}

// LocationServiceListRequest is the request payload for a location list request.
// The upstream nulink API accepts no body or parameters, so this is intentionally empty.
// TODO pro tenant anders. FITS darf beide RZ, sonst nur eines, logik dazu in nu-link
message LocationServiceListRequest {
  // Tenant to list available locations for
  // TODO Tobias baut in nulink-api ein
  string tenant = 1 [(buf.validate.field).string.(fits.api.v1.is_name) = true];
}

// LocationServiceListResponse is the response payload for a location list request
message LocationServiceListResponse {
  // The available locations
  repeated Location locations = 1;
}
