syntax = "proto3";

package fits.api.vm.v1;

import "buf/validate/validate.proto";
import "fits/api/v1/common.proto";
import "fits/api/v1/predefined_rules.proto";

// StageTypeService lists stage types available for VM instances.
// TODO wurde besprochen am 09.09.26
service StageTypeService {
  // Returns a list of all stage types available for a tenant.
  rpc List(StageTypeServiceListRequest) returns (StageTypeServiceListResponse) {
    option (fits.api.v1.project_roles) = PROJECT_ROLE_OWNER;
    option (fits.api.v1.project_roles) = PROJECT_ROLE_EDITOR;
    option (fits.api.v1.project_roles) = PROJECT_ROLE_VIEWER;
    option (fits.api.v1.auditing) = AUDITING_EXCLUDED;
  }
}

// Maps to the upstream NucleusDBStageTypes model.
message StageType {
  // Uuid of this stage type
  string uuid = 1 [(buf.validate.field).string.uuid = true];
  // title of the stage type
  string title = 2 [(buf.validate.field).string.(fits.api.v1.is_name) = true];
}

// StageTypeServiceListRequest is the request payload for a stage type list request.
// Maps to the upstream TenantInputModel.
message StageTypeServiceListRequest {}

// StageTypeServiceListResponse is the response payload for a stage type list request
message StageTypeServiceListResponse {
  // The available stage types
  repeated StageType stagetypes = 1;
}
