syntax = "proto3";

package fits.api.vm.v1;

import "buf/validate/validate.proto";
import "fits/api/v1/common.proto";
import "fits/api/v1/predefined_rules.proto";

// VMService provides VM CRUD perations.
service VMService {
  // Returns the VM with the specified UUID.
  rpc Get(VMServiceGetRequest) returns (VMServiceGetResponse) {
    option (fits.api.v1.project_roles) = PROJECT_ROLE_OWNER;
    option (fits.api.v1.project_roles) = PROJECT_ROLE_EDITOR;
    option (fits.api.v1.project_roles) = PROJECT_ROLE_VIEWER;
    option (fits.api.v1.auditing) = AUDITING_EXCLUDED;
  }
  // Creates a new VM.
  rpc Create(VMServiceCreateRequest) returns (VMServiceCreateResponse) {
    option (fits.api.v1.project_roles) = PROJECT_ROLE_OWNER;
    option (fits.api.v1.project_roles) = PROJECT_ROLE_EDITOR;
    option (fits.api.v1.auditing) = AUDITING_INCLUDED;
  }
  // Updates a VM.
  rpc Update(VMServiceUpdateRequest) returns (VMServiceUpdateResponse) {
    option (fits.api.v1.project_roles) = PROJECT_ROLE_OWNER;
    option (fits.api.v1.project_roles) = PROJECT_ROLE_EDITOR;
    option (fits.api.v1.auditing) = AUDITING_INCLUDED;
  }
  // Returns the list of all VMs.
  rpc List(VMServiceListRequest) returns (VMServiceListResponse) {
    option (fits.api.v1.project_roles) = PROJECT_ROLE_OWNER;
    option (fits.api.v1.project_roles) = PROJECT_ROLE_EDITOR;
    option (fits.api.v1.project_roles) = PROJECT_ROLE_VIEWER;
    option (fits.api.v1.auditing) = AUDITING_EXCLUDED;
  }
  // Deletes a VM.
  rpc Delete(VMServiceDeleteRequest) returns (VMServiceDeleteResponse) {
    option (fits.api.v1.project_roles) = PROJECT_ROLE_OWNER;
    option (fits.api.v1.project_roles) = PROJECT_ROLE_EDITOR;
    option (fits.api.v1.auditing) = AUDITING_INCLUDED;
  }
}

// VM Instance Messages
message VMInstance {
  // Uuid of this VM
  string uuid = 1 [(buf.validate.field).string.uuid = true];
  // Meta for this VM
  fits.api.v1.Meta meta = 2;
  // Name of this VM
  string name = 3 [(buf.validate.field).string.(fits.api.v1.is_name) = true];
  // Project where this VM belongs to
  string project = 4 [(buf.validate.field).string.uuid = true];
}

// Service messages

// VMServiceGetRequest TODO
message VMServiceGetRequest {
  // Uuid of this VM
  string uuid = 1 [(buf.validate.field).string.uuid = true];
  // Project where this VM belongs to
  string project = 2 [(buf.validate.field).string.uuid = true];
}

// VMServiceGetResponse TODO
message VMServiceGetResponse {
  // The VM
  VMInstance vm = 1;
}
// Windows-specific create request parts
message VMServiceCreateWindowsRequest {
  // Domain UUID
  string domain_uuid = 1 [(buf.validate.field).string.uuid = true];
  // // Windows Disk
  WindowsDisk disk = 2;
}

// Linux-specific create request parts
message VMServiceCreateLinuxRequest {
  // LDAP UUID
  string ldap_uuid = 1 [(buf.validate.field).string.uuid = true];
  // Linux Disk
  LinuxDisk disk = 2;
}

// VMServiceCreateRequest TODO
message VMServiceCreateRequest {
  // Project of the VM
  string project_uuid = 1 [(buf.validate.field).string.uuid = true];
  // Name of the VM
  optional string name = 2 [(buf.validate.field).string.(fits.api.v1.is_name) = true];
  // Number of CPUs of this VM
  uint32 cpu = 3;
  // RAM of the VM in GB (TODO 2^n validation)
  uint32 ram = 4;
  // OS Uuid of the OS to install in the VM instance
  string os_uuid = 5 [(buf.validate.field).string.uuid = true];
  // VLAN Uuid of the VLAN to install in the VM instance into
  string vlan_uuid = 6 [(buf.validate.field).string.uuid = true];
  // Location Uuid of the datacenter location to install in the VM instance
  string location_uuid = 7 [(buf.validate.field).string.uuid = true];
  // Contact Uuid of who is the responsible contact of the VM instance
  // TODO hier ist noch Klärungsbedarf. Ansprechpartner hängt nicht mal an einem echten user im system
  // TODO sondern sind einfach nur Kontaktdaten, die an die Entity hingehängt wird.
  // TODO aktuell hängt dies in der nulink api
  // TODO labels als Option?
  // TODO what about dsgvo?
  // TODO daten im service now?
  // TODO eventuell im tenant-apiserver Kontakte erlauben?
  // TODO was macht FCN? wäre das für sie auch sinnvoll?
  // TODO is required
  string contact_uuid = 8 [(buf.validate.field).string.uuid = true];
  // Replaces optional ContractNumber, TransactionNumber, TechnicalKey, AccountingKey
  fits.api.v1.Labels labels = 10;
  // Order number muss unbedingt mitgegeben werden
  // Hängt sogar z.b. am VM restart.
  // Wird für gewöhnlich vom User angegeben.
  string order_number = 11;
  // Currently no different backup plans, just true or false
  bool backup = 12;
  // V0, V1, V2, V3 -> highest=best
  string availability = 13;
  // SZ1, SZ2, SZ3 -> highest=best
  string serviceclass = 14;
  // TODO differentiation Linux/Windows
  oneof vmtype {
    // ensure at least one match is specified.
    option (buf.validate.oneof).required = true;
    // Windows Disk and Domain
    VMServiceCreateWindowsRequest windows = 21;
    // Linux Disk and LDAP
    VMServiceCreateLinuxRequest linux = 22;
  }
  // Disks             []DiskInputModel
  // TODO is inherited from the token making the create request -> stored in meta.createdBy
  // TODO Tobias bietet an, das Token selbst zu lesen und das RequestedBy selbst zu holen über x-original token (siehe Botonds PR)
  // RequestedBy       *string

  // Still open
  // AccountingKey     *string
  // Availability      VMInstanceLinuxCreateInputModelAvailability
  // Backup            bool
  // Billable          bool
  // BillingStartDate  *openapi_types.Date
  // Contract          bool
  // ContractNumber    *string
  // Encrypted         bool
  // LdapUuid          openapi_types.UUID
  // OrderNumber       string
  // Serviceclass      VMInstanceLinuxCreateInputModelServiceclass
  // Storageclass      VMInstanceLinuxCreateInputModelStorageclass
  // TechnicalKey      *string
  // TenantUuid        *string // TODO Defined with the projectUUID
  // TransactionNumber *string
}

// LinuxDisk
message LinuxDisk {
  // AutoExtend if set to true the disk grows automatically
  bool auto_extend = 1;
  // Size if the disk in GB
  optional uint64 size_in_gb = 2; // TODO discuss how this could be optional
  // Label of the disk
  string label = 4;
  // MountPoint where this disk should be mounted
  optional string mount_point = 5; // TODO this requires a Filesystem on the disk ?
}

// WindowsDisk
message WindowsDisk {
  // AutoExtend if set to true the disk grows automatically
  bool auto_extend = 1;
  // Size if the disk in GB
  optional uint64 size_in_gb = 2; // TODO discuss how this could be optional
  // DriveLetter where this disk should be assigned
  optional string driveletter = 3;
  // Label of the disk
  string label = 4;
}

// VMServiceCreateResponse TODO
message VMServiceCreateResponse {}

// VMServiceUpdateRequest TODO
message VMServiceUpdateRequest {
  // Project of the VM
  string project = 1 [(buf.validate.field).string.uuid = true];

  // TODO updatable fields

  // UpdateMeta contains the timestamp and strategy to be used in this update request.
  fits.api.v1.UpdateMeta update_meta = 2 [(buf.validate.field).required = true];
}

// VMServiceUpdateResponse TODO
message VMServiceUpdateResponse {}

// VMServiceListRequest TODO
message VMServiceListRequest {
  // Project of the VM
  string project = 1 [(buf.validate.field).string.uuid = true];
}

// VMServiceListResponse TODO
message VMServiceListResponse {}

// VMServiceDeleteRequest TODO
message VMServiceDeleteRequest {
  // Project of the VM
  string project = 1 [(buf.validate.field).string.uuid = true];
}

// VMServiceDeleteResponse TODO
message VMServiceDeleteResponse {}
