// @generated by protoc-gen-es v2.14.1 with parameter "target=ts,import_extension=js"
// @generated from file fits/api/v1/tenant.proto (package fits.api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb.js";
import type { Labels, Meta, UpdateLabels, UpdateMeta } from "./common_pb.js";
import { file_fits_api_v1_common } from "./common_pb.js";
import { file_fits_api_v1_predefined_rules } from "./predefined_rules_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file fits/api/v1/tenant.proto.
 */
export const file_fits_api_v1_tenant: GenFile = /*@__PURE__*/
  fileDesc("ChhmaXRzL2FwaS92MS90ZW5hbnQucHJvdG8SC2ZpdHMuYXBpLnYxIqwBCgZUZW5hbnQSDQoFbG9naW4YASABKAkSHwoEbWV0YRgCIAEoCzIRLmZpdHMuYXBpLnYxLk1ldGESGQoEbmFtZRgDIAEoCUILukgIcgbAs66xAgESDQoFZW1haWwYBCABKAkSIAoLZGVzY3JpcHRpb24YBSABKAlCC7pICHIGyLOusQIBEhIKCmF2YXRhcl91cmwYBiABKAkSEgoKY3JlYXRlZF9ieRgHIAEoCSKQAQoYVGVuYW50U2VydmljZUxpc3RSZXF1ZXN0Eg8KAmlkGAEgASgJSACIAQESHgoEbmFtZRgCIAEoCUILukgIcgbAs66xAgFIAYgBARIoCgZsYWJlbHMYAyABKAsyEy5maXRzLmFwaS52MS5MYWJlbHNIAogBAUIFCgNfaWRCBwoFX25hbWVCCQoHX2xhYmVscyIpChdUZW5hbnRTZXJ2aWNlR2V0UmVxdWVzdBIOCgZ0ZW5hbnQYASABKAkizAIKGlRlbmFudFNlcnZpY2VVcGRhdGVSZXF1ZXN0Eg4KBnRlbmFudBgBIAEoCRI0Cgt1cGRhdGVfbWV0YRgCIAEoCzIXLmZpdHMuYXBpLnYxLlVwZGF0ZU1ldGFCBrpIA8gBARIeCgRuYW1lGAMgASgJQgu6SAhyBsCzrrECAUgAiAEBEhsKBWVtYWlsGAQgASgJQge6SARyAmABSAGIAQESJQoLZGVzY3JpcHRpb24YBSABKAlCC7pICHIGyLOusQIBSAKIAQESFwoKYXZhdGFyX3VybBgGIAEoCUgDiAEBEi4KBmxhYmVscxgHIAEoCzIZLmZpdHMuYXBpLnYxLlVwZGF0ZUxhYmVsc0gEiAEBQgcKBV9uYW1lQggKBl9lbWFpbEIOCgxfZGVzY3JpcHRpb25CDQoLX2F2YXRhcl91cmxCCQoHX2xhYmVscyI/ChhUZW5hbnRTZXJ2aWNlR2V0UmVzcG9uc2USIwoGdGVuYW50GAEgASgLMhMuZml0cy5hcGkudjEuVGVuYW50IkEKGVRlbmFudFNlcnZpY2VMaXN0UmVzcG9uc2USJAoHdGVuYW50cxgBIAMoCzITLmZpdHMuYXBpLnYxLlRlbmFudCJCChtUZW5hbnRTZXJ2aWNlVXBkYXRlUmVzcG9uc2USIwoGdGVuYW50GAEgASgLMhMuZml0cy5hcGkudjEuVGVuYW50MrsCCg1UZW5hbnRTZXJ2aWNlEl8KBExpc3QSJS5maXRzLmFwaS52MS5UZW5hbnRTZXJ2aWNlTGlzdFJlcXVlc3QaJi5maXRzLmFwaS52MS5UZW5hbnRTZXJ2aWNlTGlzdFJlc3BvbnNlIgjY8xgC4PMYAhJgCgNHZXQSJC5maXRzLmFwaS52MS5UZW5hbnRTZXJ2aWNlR2V0UmVxdWVzdBolLmZpdHMuYXBpLnYxLlRlbmFudFNlcnZpY2VHZXRSZXNwb25zZSIMwvMYBAECAwTg8xgCEmcKBlVwZGF0ZRInLmZpdHMuYXBpLnYxLlRlbmFudFNlcnZpY2VVcGRhdGVSZXF1ZXN0GiguZml0cy5hcGkudjEuVGVuYW50U2VydmljZVVwZGF0ZVJlc3BvbnNlIgrC8xgCAQLg8xgBQpcBCg9jb20uZml0cy5hcGkudjFCC1RlbmFudFByb3RvUAFaKWdpdGh1Yi5jb20vZmktdHMvYXBpL2dvL2ZpdHMvYXBpL3YxO2FwaXYxogIDRkFYqgILRml0cy5BcGkuVjHKAgtGaXRzXEFwaVxWMeICF0ZpdHNcQXBpXFYxXEdQQk1ldGFkYXRh6gINRml0czo6QXBpOjpWMWIGcHJvdG8z", [file_buf_validate_validate, file_fits_api_v1_common, file_fits_api_v1_predefined_rules]);

/**
 * Tenant is a customer of the platform
 *
 * @generated from message fits.api.v1.Tenant
 */
export type Tenant = Message<"fits.api.v1.Tenant"> & {
  /**
   * Login of the tenant
   *
   * @generated from field: string login = 1;
   */
  login: string;

  /**
   * Meta for this tenant
   *
   * @generated from field: fits.api.v1.Meta meta = 2;
   */
  meta?: Meta | undefined;

  /**
   * Name of the tenant
   *
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * Email of the tenant
   *
   * @generated from field: string email = 4;
   */
  email: string;

  /**
   * Description of this tenant
   *
   * @generated from field: string description = 5;
   */
  description: string;

  /**
   * AvatarUrl of the tenant
   *
   * @generated from field: string avatar_url = 6;
   */
  avatarUrl: string;

  /**
   * CreatedBy stores who created this tenant
   *
   * @generated from field: string created_by = 7;
   */
  createdBy: string;
};

/**
 * Describes the message fits.api.v1.Tenant.
 * Use `create(TenantSchema)` to create a new message.
 */
export const TenantSchema: GenMessage<Tenant> = /*@__PURE__*/
  messageDesc(file_fits_api_v1_tenant, 0);

/**
 * TenantServiceListRequest is the request payload of the tenant list request
 *
 * @generated from message fits.api.v1.TenantServiceListRequest
 */
export type TenantServiceListRequest = Message<"fits.api.v1.TenantServiceListRequest"> & {
  /**
   * Id filters tenants by id
   *
   * @generated from field: optional string id = 1;
   */
  id?: string | undefined;

  /**
   * Name filters tenants by name
   *
   * @generated from field: optional string name = 2;
   */
  name?: string | undefined;

  /**
   * Labels lists only projects containing the given labels
   *
   * @generated from field: optional fits.api.v1.Labels labels = 3;
   */
  labels?: Labels | undefined;
};

/**
 * Describes the message fits.api.v1.TenantServiceListRequest.
 * Use `create(TenantServiceListRequestSchema)` to create a new message.
 */
export const TenantServiceListRequestSchema: GenMessage<TenantServiceListRequest> = /*@__PURE__*/
  messageDesc(file_fits_api_v1_tenant, 1);

/**
 * TenantServiceGetRequest is the request payload of the tenant get request
 *
 * @generated from message fits.api.v1.TenantServiceGetRequest
 */
export type TenantServiceGetRequest = Message<"fits.api.v1.TenantServiceGetRequest"> & {
  /**
   * Tenant is the login of the tenant
   *
   * @generated from field: string tenant = 1;
   */
  tenant: string;
};

/**
 * Describes the message fits.api.v1.TenantServiceGetRequest.
 * Use `create(TenantServiceGetRequestSchema)` to create a new message.
 */
export const TenantServiceGetRequestSchema: GenMessage<TenantServiceGetRequest> = /*@__PURE__*/
  messageDesc(file_fits_api_v1_tenant, 2);

/**
 * TenantServiceUpdateRequest is the request payload of the tenant update request
 *
 * @generated from message fits.api.v1.TenantServiceUpdateRequest
 */
export type TenantServiceUpdateRequest = Message<"fits.api.v1.TenantServiceUpdateRequest"> & {
  /**
   * Tenant is the login of the tenant
   *
   * @generated from field: string tenant = 1;
   */
  tenant: string;

  /**
   * UpdateMeta contains the timestamp and strategy to be used in this update request
   *
   * @generated from field: fits.api.v1.UpdateMeta update_meta = 2;
   */
  updateMeta?: UpdateMeta | undefined;

  /**
   * Name of the tenant
   *
   * @generated from field: optional string name = 3;
   */
  name?: string | undefined;

  /**
   * Email of the tenant
   *
   * @generated from field: optional string email = 4;
   */
  email?: string | undefined;

  /**
   * Description of this tenant
   *
   * @generated from field: optional string description = 5;
   */
  description?: string | undefined;

  /**
   * AvatarUrl of the tenant
   *
   * @generated from field: optional string avatar_url = 6;
   */
  avatarUrl?: string | undefined;

  /**
   * Labels on the tenant
   *
   * @generated from field: optional fits.api.v1.UpdateLabels labels = 7;
   */
  labels?: UpdateLabels | undefined;
};

/**
 * Describes the message fits.api.v1.TenantServiceUpdateRequest.
 * Use `create(TenantServiceUpdateRequestSchema)` to create a new message.
 */
export const TenantServiceUpdateRequestSchema: GenMessage<TenantServiceUpdateRequest> = /*@__PURE__*/
  messageDesc(file_fits_api_v1_tenant, 3);

/**
 * TenantServiceGetResponse is the response payload of the tenant get request
 *
 * @generated from message fits.api.v1.TenantServiceGetResponse
 */
export type TenantServiceGetResponse = Message<"fits.api.v1.TenantServiceGetResponse"> & {
  /**
   * Tenant is the tenant
   *
   * @generated from field: fits.api.v1.Tenant tenant = 1;
   */
  tenant?: Tenant | undefined;
};

/**
 * Describes the message fits.api.v1.TenantServiceGetResponse.
 * Use `create(TenantServiceGetResponseSchema)` to create a new message.
 */
export const TenantServiceGetResponseSchema: GenMessage<TenantServiceGetResponse> = /*@__PURE__*/
  messageDesc(file_fits_api_v1_tenant, 4);

/**
 * TenantServiceListResponse is the response payload of the tenant list request
 *
 * @generated from message fits.api.v1.TenantServiceListResponse
 */
export type TenantServiceListResponse = Message<"fits.api.v1.TenantServiceListResponse"> & {
  /**
   * Tenants is the list of tenants
   *
   * @generated from field: repeated fits.api.v1.Tenant tenants = 1;
   */
  tenants: Tenant[];
};

/**
 * Describes the message fits.api.v1.TenantServiceListResponse.
 * Use `create(TenantServiceListResponseSchema)` to create a new message.
 */
export const TenantServiceListResponseSchema: GenMessage<TenantServiceListResponse> = /*@__PURE__*/
  messageDesc(file_fits_api_v1_tenant, 5);

/**
 * TenantServiceUpdateResponse is the response payload of the tenant update request
 *
 * @generated from message fits.api.v1.TenantServiceUpdateResponse
 */
export type TenantServiceUpdateResponse = Message<"fits.api.v1.TenantServiceUpdateResponse"> & {
  /**
   * Tenant is the tenant
   *
   * @generated from field: fits.api.v1.Tenant tenant = 1;
   */
  tenant?: Tenant | undefined;
};

/**
 * Describes the message fits.api.v1.TenantServiceUpdateResponse.
 * Use `create(TenantServiceUpdateResponseSchema)` to create a new message.
 */
export const TenantServiceUpdateResponseSchema: GenMessage<TenantServiceUpdateResponse> = /*@__PURE__*/
  messageDesc(file_fits_api_v1_tenant, 6);

/**
 * TenantService provides tenant management operations.
 *
 * @generated from service fits.api.v1.TenantService
 */
export const TenantService: GenService<{
  /**
   * Returns the list of tenants.
   *
   * @generated from rpc fits.api.v1.TenantService.List
   */
  list: {
    methodKind: "unary";
    input: typeof TenantServiceListRequestSchema;
    output: typeof TenantServiceListResponseSchema;
  },
  /**
   * Get a tenant
   *
   * @generated from rpc fits.api.v1.TenantService.Get
   */
  get: {
    methodKind: "unary";
    input: typeof TenantServiceGetRequestSchema;
    output: typeof TenantServiceGetResponseSchema;
  },
  /**
   * Update a tenant
   *
   * @generated from rpc fits.api.v1.TenantService.Update
   */
  update: {
    methodKind: "unary";
    input: typeof TenantServiceUpdateRequestSchema;
    output: typeof TenantServiceUpdateResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_fits_api_v1_tenant, 0);

